### ISSUE TITLE
Import into Eclipse doesn't work out of the box

### ISSUE THREAD

**Issue by wilkinsona** [reactor/reactor#100]
From @markpollack:

> importing project into eclipse...  ./gradlew cleanEclipse eclipse  doesn't quite work out of the box.  i tried to change the project nature to java afterwards but that didn't help.  Adding:
allprojects { 
     apply plugin: 'eclipse' 
    apply plugin: 'java'
}
got me a bit closer, but no dep libraries and no src libraries populated.

**Comment by ifesdjeen** [comment]
This one was fixed lately thanks to @bripkens

**Comment by bripkens** [comment]
Hm, `apply plugin` is still necessary and would make it easier for Eclipse users. @ifesdjeen: I could add this step and document the Eclipse configurations in order to get new contributors up and running. Would that be interesting for you guys?

**Comment by smaldini** [comment]
Of course Ben you're super welcome as usual now :) Related small note, an internal change is being experimented to promote reactor-stream as an individual repo so I'll backport what you want to propose into it (we've already started doing that with reactor/reactor-core)

**Comment by bripkens** [comment]
@smaldini: Shall I split this into multiple commits then, i.e. one per project, so that it is easier for you to port the changes to the new repositories?

**Comment by smaldini** [comment]
If you have extra time but don't try hard I can walkthrough it myself
