### ISSUE TITLE
Provide an easy way, to wait for all current tasks to complete

### ISSUE THREAD

**Issue by allnightlong** [reactor/reactor#172]
Currently, in all benchmarks/test/examples there is ugly CountDownLatch.
It's used inside Consumer, messing with the main code.

I think, there should be some kind of await() method, which is waiting for completion of all current task.

**Comment by Chumper** [comment]
Is there an equivalent in Reactor 2.x? I haven't found Boundary in 2.x
I have the use case that i will notify on a given key and need to wait for all consumers to be completed.
`Eventbus.sendAndReceive` will complete after the first arrival of any consumer reply and i havent found a way to do this with streams.

Is there any example on this?

**Comment by smaldini** [comment]
A quick idea if you want to```groovy
def bus = EventBus.create()

//attach bus consumer
int i = 1
bus.on($('test')){
   ((Subscriber)it.replyTo).onNext("hello "+ (i++))
}

//publish an event where we want 5 answers
def broadcaster = Broadcaster.create()

broadcaster
   .take(5)
   .consume { event ->
       println event
   }
}

bus.notify('test', Event.wrap('some').replyTo(broadcaster))
```

**Comment by Chumper** [comment]
@smaldini: The problem is that i dont know exactly how many consumers can respond to my message.
Can i use `take` in that case and have a timeout, like 2 seconds?

I need to wait for n consumers and want to use all responses but only up to 2 seconds, if you want a specific use case. is that possible with your construct?

**Comment by smaldini** [comment]
you can use take(2, TimeUnit.SECONDS) but that would leave that open for 2 seconds always. 
Or you can wait for 2 seconds as soon as there is no data (timeout) :
```groovy
broadcaster
   .timeout(2, TimeUnit.Seconds, Streams.empty()) // note that the third argument is what happens when 2 seconds have been elapsed without data, in this case we close the stream
   .consume { event ->
       println event
   }
```

**Comment by Chumper** [comment]
Ok, thanks,somy use case is not directly possible. i will see if i can experiment with the `take` and `timeout` method and see if i can get it to work.

**Comment by jbrisbin** [comment]
I was just experimenting today with a `BarrierStream` which is a special `Stream<List<Object>>` subclass that allows you to bind an arbitrary `Function` and `Consumer` to it and only get notified of the values when all bound tasks are completed. The values in the `List` correspond to the functions and consumers bound into the stream.

An example of how this would look is something like this:

```java
EventBus bus;

BarrierStream barrierStream = new BarrierStream();

bus.on($("hello"), barrierStream.wrap((Event<String> ev) -> {
  System.out.println("got in bus: " + ev.getData());
}));

Streams.just("Hello World!")
       .map(barrierStream.wrap((Function<String, String>) String::toUpperCase))
       .consume(s -> {
         System.out.println("got in stream: " + s);
       });

barrierStream.consume(vals -> {
  System.out.println("got vals: " + vals);
});

bus.notify("hello", Event.wrap("Hello World!"));
```

Since the `Consumer<Event<?>>` is bound first, the first slot in the values `List` will be the `Event<?>`. The second slot would be the string "HELLO WORLD!" and would be put into the values list first since it's available immediately, unlike the `Event` which is only available later.

**Comment by Chumper** [comment]
That sounds interesting, let me know when it's ready, i would be glad to test and use it.

**Comment by ssosasae** [comment]
Have some one found a way to do it?

![diapositiva1](https://cloud.githubusercontent.com/assets/15238806/14905358/aaec87fa-0d64-11e6-8ac1-51c43406a7b3.JPG)
![diapositiva2](https://cloud.githubusercontent.com/assets/15238806/14905359/aaecd73c-0d64-11e6-82fd-0e702227dda0.JPG)
![diapositiva3](https://cloud.githubusercontent.com/assets/15238806/14905361/aaed0f2c-0d64-11e6-977b-6f15a0a1d72e.JPG)
![diapositiva4](https://cloud.githubusercontent.com/assets/15238806/14905360/aaed0176-0d64-11e6-8f6d-debb0a9385d6.JPG)
![diapositiva5](https://cloud.githubusercontent.com/assets/15238806/14905362/aaefc352-0d64-11e6-9cd2-4f5958a95123.JPG)
![diapositiva6](https://cloud.githubusercontent.com/assets/15238806/14905363/aaf17030-0d64-11e6-91e5-d1fa7cedb732.JPG)
![diapositiva7](https://cloud.githubusercontent.com/assets/15238806/14905364/ab01c214-0d64-11e6-873c-bd7cf454b2c5.JPG)

**Comment by sergio990z** [comment]
Have some one found a way to do it?

Im trying the Broadcast, but don't undertood how use it.

I think I need Future, Streams and Consumers.
Using only EventBusI don't think this work.

Event-Bus Request/Reply send the response to another suscriptor ( on.event)
http://projectreactor.io/old/reference/#bus-request-reply

for example:

`bus.send("job.sink", Event.wrap("Hello World!", "reply.sink"));`

but the response will be sento to " "reply.sink"".

"reply.sink" is another subscription. Im looking for some kind of REQUEST-RESPONSE and WAIT untill the other messages arrived.. then response ...

I was learning with the documentation:
http://projectreactor.io/old/reference/#bus-request-reply
http://projectreactor.io/ext/docs/api/



Some images to get the idea:


![diapositiva1](https://cloud.githubusercontent.com/assets/18729269/14905644/6d0bea0e-0d67-11e6-8286-87ea46332c15.JPG)
![diapositiva2](https://cloud.githubusercontent.com/assets/18729269/14905643/6d0bdde8-0d67-11e6-8cf2-7ec4a012d545.JPG)
![diapositiva3](https://cloud.githubusercontent.com/assets/18729269/14905641/6d0bb07a-0d67-11e6-85a4-0793bb66ab26.JPG)
![diapositiva4](https://cloud.githubusercontent.com/assets/18729269/14905642/6d0bbe62-0d67-11e6-99cb-f36b9b057d49.JPG)
![diapositiva5](https://cloud.githubusercontent.com/assets/18729269/14905645/6d0c4418-0d67-11e6-9898-23c45e6054e5.JPG)
![diapositiva6](https://cloud.githubusercontent.com/assets/18729269/14905646/6d10add2-0d67-11e6-9cb2-acefc09659b8.JPG)
![diapositiva7](https://cloud.githubusercontent.com/assets/18729269/14905647/6d1fafbc-0d67-11e6-9bee-1831fa392a7f.JPG)



Have some idea how synchronice, wait and get the chained messages?
