### ISSUE TITLE
[reactor-queue] move to chronicle 2.0

### ISSUE THREAD

**Issue by lburgazzoli** [reactor/reactor#183]
Upgrade  Java-Chronicle to v2.0

* 1.x https://github.com/peter-lawrey/Java-Chronicle
* 2.x https://github.com/OpenHFT/Java-Chronicle

**Comment by bripkens** [comment]
Looks like this issue is resolved since Reactor is now at Chronicle 3.4.2 [1].

[1] https://github.com/reactor/reactor/blob/70158875d1ef564e26864ef7627ec72d3de0a261/build.gradle#L52

**Comment by ifesdjeen** [comment]
:+1: @bripkens
