### ISSUE TITLE
UDP Client Support

### ISSUE THREAD

**Issue by sohailalam2** [reactor/reactor#357]
Hi...
I am new to Reactor and was looking to find some abstract implementation of UDP Client (specifically for UDP multicast), but could not find any.

All I found was a 

``` java
DatagramServer
```

 Is there any **DatagramClient** that I may use? Or do I have to use Netty to write one myself?

It would be really helpful to have such an abstract implementation or a helper class, that uses Netty and Disruptor internally.

Please guide me through this.

Thanks

**Comment by distopik** [comment]
+1

there is a `NetStreams.udpServer` and `NetStreams.tcpClient` but no `NetStreams.udpClient`
