### ISSUE TITLE
Is there provides a way to add transactional event publish in spring?

### ISSUE THREAD

**Issue by bobwenx** [reactor/reactor#359]
for example, in my spring application, i want to add an entity to database, and publish an event via reactor, is there provides a way to let reactor publish event only when transaction committed?
an example for this is org.springframework.cache.ehcache.EhCacheCacheManager, which can be configure to transaction aware, and only commit cache when transaction is commited.

though i can apply compensatory action after event publish/transactional failure, but it will be difficult(even impossible) to implement in business side.

**Comment by bwzhang2011** [comment]
@smaldini, how does this going on ? we're looking forward to any good integration for reactor does for spring transaction management.

**Comment by beihaifeiwu** [comment]
+1

**Comment by ffazil** [comment]
+1

**Comment by bwzhang2011** [comment]
@smaldini, any update with such issue ? by the way, thanks very very much for your team for great work for reactor 2.0 releasing and continuous improvement for it.

**Comment by smaldini** [comment]
We're working on Spring updates with the folks so this is going to be on the priority list, I'll discuss with them soon.
