### ISSUE TITLE
Add support for Secured Consumer - Spring Security

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor#361]
Initial discussions have started with @rwinch from Spring Security to nail down how to secure Reactor various consumers (or a given processing Stream).

A reference to the issue in Spring Sec can be found here: https://jira.spring.io/browse/SEC-2694.

Initial ideas to explore:
- Wrap a given Consumer into a SecuredConsumer that takes care of checking after the principal and/or populate the principal
- @ Secured method to work on an arbitrary Principal
- Provide for read support to the actual Principal from within the consumer
- Provide for automatic correlation between an ID and a Principal in a dedicated Dispatcher and/or Stream operation

**Comment by ffazil** [comment]
+1

**Comment by JanStureNielsen** [comment]
+1 I just hit this issue with `reactor-bus-2.0.7.RELEASE` -- I roll my own solution but it'd be much nicer and more portable if I didn't have to...
