### ISSUE TITLE
java.util.NoSuchElementException while closing TCP connection

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor#384]
The full stack trace can be seen in this example CI build failure https://build.spring.io/browse/SPR-PUB-JOB1-1715/test/case/135247530.

For a bit more context, here we proactively close the TCP connection upon having successfully sent a DISCONNECT frame to the STOMP broker. The broker may do the same on its side which depending on the exactly timing might probably leads to the stacktrace.

Note that I've added a try-catch around the call to close the TCP connection which should stop the test failure. Nevertheless it could be an option to the same in reactor-net as well.

**Comment by smaldini** [comment]
Cannot reproduce since 2.0.1.RELEASE
