### ISSUE TITLE
how about some support for transaction around stream pipeline ?

### ISSUE THREAD

**Issue by bwzhang2011** [reactor/reactor#385]
As reactor provide some function way to pipeline several process into a pipeline. so would you mind adding transaction support for the pipeline processing.  just like once set some transacted tag to refer to the transactionManager. it would make sure those will be invoked around the transaction.

similar like the camel framework done:
 TProcessor1 p1 = new TProcessor1();  
        from("jms:queue:TOOL.DEFAULT")  
        .transacted()  
        .log("+++ before database +++")  
        .bean(SQLBean.class, "toSql")  
        .to("jdbc:myDataSource")  
        .process(p1)  
        .log("+++ after database +++");  

just like the transacted() brought in with the transaction support. I don't know whether it could be integrated in some better way or provide some example to show how to control it.

**Comment by bwzhang2011** [comment]
@jbrisbin , how does this going on ? any plan for reactor integration with spring transaction or it should be done in reactor-spring module.

**Comment by jbrisbin** [comment]
This discussion should really be held in the reactor-spring repo, not here, since none of this is applicable outside a Spring environment.

**Comment by bwzhang2011** [comment]
@jbrisbin, I do agree with you and hope such could be wrapped in reactor-spring module.
