### ISSUE TITLE
Cross JVM events using Reactor

### ISSUE THREAD

**Issue by ffazil** [reactor/reactor#389]
Can i use Reactor to publish events across multiple JVM's?

**Comment by syamsathyan** [comment]
@jbrisbin, is there any updates on the Cross JVM abstract layer / lambda pipeline to the RabbitMQ AMQP queue? I work with ffazil (the original issue was opened on Oct 28, 2014).

**Comment by jbrisbin** [comment]
@syamsathyan There has been some work recently on getting AMQP support using streams up and running. We've been working on the @reactive-ipc project to create a Reactive Streams implementation that supports multiple transports. We've actually made some good progress on defining how that should work and many of the lessons learned along the way relate directly to using AMQP with Reactive Streams.

I hope to have some time in the next couple weeks to start translating some of those techniques to the reactive-amqp project. My initial experiments have been very positive but there are some definite hurdles to overcome. Hopefully @smaldini and I can put something useful together to start working as a base we can iterate on.

**Comment by syamsathyan** [comment]
@jbrisbin thanks for the update, we will definitely checkout the @reactive-ipc. The move have integration points for akka and Rx-Java is highly appreciated.
