### ISSUE TITLE
Building 1.1.5.RELEASE fails intermittently

### ISSUE THREAD

**Issue by wilkinsona** [reactor/reactor#394]
As part of the Spring IO Platform release process, I build Reactor 1.1.5.RELEASE (the version that's currently in the Platform). The build fails intermittently when building against the Spring IO Platform versions of Reactor's dependencies and when using Reactor's own versions. This test also fails intermittently on the CI server: https://build.spring.io/browse/REACTOR-CORE-217946/test

I'm building on OS X 10.9.5 using Java 1.8.0_25.

**Comment by smaldini** [comment]
Is it fixed in 1.1.6 ? Or should we just ignore that test and mark the issue resolved in 2.x ?

**Comment by wilkinsona** [comment]
Looks like there are still several intermittent failures in 1.1.x: https://build.spring.io/browse/REACTOR-CORE;jsessionid=147B464A8EFDFDD813B0EC1BC18288BD. IMO, ignoring the tests isn't a good solution and the underlying problems really ought to be fixed
