### ISSUE TITLE
IndexedChronicleQueuePersistor not compatible with  the latest chronicle-queue

### ISSUE THREAD

**Issue by bwzhang2011** [reactor/reactor#396]
@jbrisbin , I found IndexedChronicleQueuePersistor  is not compatible with the latest chronicle-queue since it released the 3.3 version (or afterwards).  please take a look at  https://github.com/OpenHFT/Chronicle-Queue/issues/105. as IndexedChronicle constructor has changed with ChronicleQueueBuilder brought in.

**Comment by smaldini** [comment]
Updated in last snapshot
