### ISSUE TITLE
Stream Configuration DSL in Groovy to Build DAG / Computational Flow Graph

### ISSUE THREAD

**Issue by sirinath** [reactor/reactor#410]
Can we have a Stream config DSL to build DAG / computational flow graph like in:

http://noflojs.org/documentation/json/
http://akka.io/news/2014/09/12/akka-streams-0.7-released.html
http://www.nextflow.io/

Hand rolling all the interconnections is a pain point.

@smaldini Any thoughts on something like this being added?

**Comment by Bridgescraft** [comment]
I know there is: https://github.com/reactor/reactor-graph which has a baseline implementation of the proper constructs in order to create a DAG with Reactor, however, it is based on 1.1.0.BUILD-SNAPSHOT and has not been updated for 2.0.0.

**Comment by smaldini** [comment]
We have a plan to study a query language to use in many other project to generate streams, e.g. in Spring XD.
That is something looking like " select x.id, x.name where x.id > 10 aggregated by time 5 seconds"
The result of such query would be a generated stream like:
```java  stream.filter( x -> x.id > 10).map(x -> Tuple.of(x.id, x.name)).buffer(5, TimeUnit.Seconds) ```
