### ISSUE TITLE
Straighten support for connecting to different addresses in NetClient

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor#412]
NetClient has `open()` and `open(Reconnect)`. Neither accepts an address so the implicit assumption is connecting to the same (default) address. However a `Reconnect` strategy can provide a new address so you could end up with simultaneous connections to different addresses. For example remote host closes 1 connection (of many) and that connection reconnects to a new address.

In the implementation, the base class TcpClient has a final field connectAddress. The sub-class NettyTcpClient adds its own volatile connectAddress presumably to support reconnect but that's ignored (see #379). Perhaps the idea was for the nested ReconnectChannlerListener class to reconnect without affecting the base class' connectAddress? In effect it means the connectAddress in the base class isn't the address we always connect to but rather a "default" address to use.

Looking at Netty Bootstrap it has `connect()`, which expects the remoteAddress property to be set in advance. It also has other connect methods that accept any address. So the underlying API seems to allow connecting to any address at any time (e.g. I can call `connect()` and `connect(SocketAddress)` in any sequence). Is there a reason NettyTcpClient (and probably NetClient) couldn't work that way too? 

The alternative today is to use a separate TcpClient instance per connection with a shared EventLoopGroup. That seems like more work than should be necessary.

**Comment by jkubrynski** [comment]
Any progress with this issue?

**Comment by sprgn** [comment]
Why was this issue closed?  Was the support added?

**Comment by rstoyanchev** [comment]
I'm not sure this issue is superseded by anything. This one is about having a reconnect strategy that can reconnect to a different address than the original one. @smaldini, is it possible to do, or do we need to re-create this ticket against the current reactor-netty project?

**Comment by smaldini** [comment]
Could use retry, best to mark it in 0.8 so we make sure the APi doesn’t prevent it. We already support supplier of inetadress in options.
