### ISSUE TITLE
Streams and workQueue broken after 1.1.3

### ISSUE THREAD

**Issue by jfgosselin** [reactor/reactor#424]
The following stream works with 1.1.3.RELEASE , but with 1.1.4.RELEASE or 1.1.5.RELEASE it stops after the Predicate. Bug ?
 

    Environment env = new Environment();
    Deferred<String, Stream<String>> deferred = Streams.<String> defer(env, env.getDispatcher("workQueue"));
    Stream<String> stream = deferred.compose();

    stream.map(new Function<String, String>() {
      @Override
      public String apply(String task) {
        LOGGER.info("First funcion:" + task);
        return task;
      }
    }).filter(new Predicate<String>() {

      @Override
      public boolean test(String task) {
        LOGGER.info("Predicate:" + task);
        return true;
      }
    }).map(new Function<String, String>() {

      @Override
      public String apply(String task) {
        LOGGER.info("Second funcion:" + task);
        return task;
      }
    }).consume(new Consumer<String>() {
      @Override
      public void accept(final String task) {
        LOGGER.info("Consumed " + task);
      }
    });

    deferred.accept("Try this");

**Comment by jfgosselin** [comment]
Did you have chance to reproduce this issue ?

**Comment by smaldini** [comment]
Not yet we're head down on RC1 preparation (which looks like reactor-core 2.0 snapshot in its current state).

The Stream has notably changed a lot syntax wise but every use case are ported and it just works the same in a constistent and x5 faster fashion, let me know if you need an example of this in new version.

**Comment by smaldini** [comment]
Updated in 2.0.1 and 2.0.2.RELEASE, doc http://projectreactor.io/docs/reference/#streams-multithreading
