### ISSUE TITLE
reactor-logback README.md incorrectly states that there are no reactor dependencies

### ISSUE THREAD

**Issue by philsttr** [reactor/reactor#426]
The first line of [reactor-logback's README.md](https://github.com/reactor/reactor/blob/master/reactor-logback/README.md) states:

> The reactor-logback module is somewhat misleadingly-named. There are no Reactor dependencies in it. 

When, in fact, reactor-logback DOES depend on reactor.

This is easily seen in the reactor-logback's pom file in maven central:

```xml
     <dependency>
      <groupId>org.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
      <version>1.1.5.RELEASE</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>commons-logging</artifactId>
          <groupId>commons-logging</groupId>
        </exclusion>
      </exclusions>
    </dependency>
```

And in import statements in the [AsyncAppender](https://github.com/reactor/reactor/blob/master/reactor-logback/src/main/java/reactor/logback/AsyncAppender.java#L24)...

```java
import reactor.core.dispatch.processor.Operation;
import reactor.core.dispatch.processor.Processor;
import reactor.core.dispatch.processor.spec.ProcessorSpec;
import reactor.fn.Consumer;
import reactor.fn.Supplier;
```

Please either
A. Correct the documentation, or
B. Remove the dependency on reactor (and just use the disruptor directly).

I would much prefer B, since my projects don't use reactor for anything else.  But I can understand why you would want to use reactor, since this is a sub-module of reactor itself.

**Comment by jbrisbin** [comment]
I updated the README to reflect the use of Reactor's `Processor` and updated the artifact coordinates to the latest.
