### ISSUE TITLE
Execution stops almost 15 seconds

### ISSUE THREAD

**Issue by leosilvadev** [reactor/reactor#431]
Hi, currently I'm having a problem using Reactor integrated with Spring and Quartz.
In the project I have a Scheduler that execute Jobs (registered in database) every 500 ms, then I execute all my Jobs with Reactor, but after some seconds (kind of 30 sec) the executor stops for 15 seconds and then start again.
I'm really newbie using Reactor, so sorry if I'm missing some specific behavior or even a missing configuration.

Currently I have configured my Reactor in a default Environment and using EventLoop.

**Comment by smaldini** [comment]
which version ?

**Comment by leosilvadev** [comment]
Reactor at version 1.1.5.RELEASE and Reactor-Spring version 1.0.1.RELEASE

**Comment by smaldini** [comment]
If you're new to Reactor consider using 2.0 build snapshot to become RC1 in a couple days, let me know if you can paste your code so I assist you with the syntax in the newest version or just try to read the issue.

**Comment by leosilvadev** [comment]
Ok, my current configuration:
```
@Bean
	public Reactor jobsReactor(){
		Environment environment = new Environment();
		return Reactors.reactor().env(environment).dispatcher(Environment.EVENT_LOOP).get();
	}
```


My Schedulers work as this:
```
@Scheduled(fixedDelay=500)
	public void executeJobs() throws Exception{
		Collection<Job> jobs = jobService.findAllActives();
		
		for(Job job : jobs){ jobsReactor.notify("job.execute", Event.wrap(job)); }
	}
```

And my Selector as:
```
@Selector(value="job.execute", reactor="@jobsReactor")
	public void execute(Event<Job> event) throws Exception{
		Job job = event.getData();
		pingJobService.lockJob(job);
		pingJobService.execute(job);
		pingJobService.unlockJob(job);
	}
```

**Comment by leosilvadev** [comment]
I'll try to get the recent version, but I started to get the version 1.1.5 because the cliente where I work on have a lot of issues about 'security', so they block a lot of new dependecies (I need to use JDK6), I frequently have to get the libs available at maven central repository.

**Comment by jbrisbin** [comment]
You should probably be using the 1.1.5 reactor-spring as well.

That behavior seems very strange. It sounds like something is blocking the RingBuffer and timing out (maybe recursively)?

**Comment by leosilvadev** [comment]
Look, how it's working now:

Executing scheduler, 3 jobs found. Fri Feb 06 14:45:40 BRST 2015
Executing Ping... Fri Feb 06 14:45:40 BRST 2015
Executing Ping... Fri Feb 06 14:45:40 BRST 2015
Executing Ping... Fri Feb 06 14:45:40 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:40 BRST 2015
Executing Ping... Fri Feb 06 14:45:40 BRST 2015
Executing Ping... Fri Feb 06 14:45:41 BRST 2015
Executing Ping... Fri Feb 06 14:45:41 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:41 BRST 2015
Executing Ping... Fri Feb 06 14:45:41 BRST 2015
Executing Ping... Fri Feb 06 14:45:41 BRST 2015
Executing Ping... Fri Feb 06 14:45:41 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:41 BRST 2015
Executing Ping... Fri Feb 06 14:45:41 BRST 2015
Executing Ping... Fri Feb 06 14:45:41 BRST 2015
Executing Ping... Fri Feb 06 14:45:41 BRST 2015
Executing scheduler, 4 jobs found. Fri Feb 06 14:45:42 BRST 2015
Executing Ping... Fri Feb 06 14:45:42 BRST 2015
Executing Ping... Fri Feb 06 14:45:42 BRST 2015
Executing Ping... Fri Feb 06 14:45:42 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:42 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:43 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:44 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:44 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:45 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:45 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:46 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:46 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:47 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:47 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:48 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:48 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:49 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:49 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:50 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:50 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:51 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:51 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:52 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:52 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:53 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:53 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:54 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:54 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:55 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:55 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:56 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:56 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:57 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:57 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:58 BRST 2015
Executing scheduler, 4 jobs found. Fri Feb 06 14:45:58 BRST 2015
Executing scheduler, 4 jobs found. Fri Feb 06 14:45:59 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:45:59 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:46:00 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:46:00 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:46:01 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:46:01 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:46:02 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:46:02 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:46:03 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:46:03 BRST 2015
Executing Ping... Fri Feb 06 14:46:03 BRST 2015
Executing Ping... Fri Feb 06 14:46:03 BRST 2015
Executing Ping... Fri Feb 06 14:46:03 BRST 2015
Executing Ping... Fri Feb 06 14:46:03 BRST 2015
Executing Ping... Fri Feb 06 14:46:04 BRST 2015
Executing Ping... Fri Feb 06 14:46:04 BRST 2015
Executing Ping... Fri Feb 06 14:46:04 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:46:04 BRST 2015
Executing Ping... Fri Feb 06 14:46:04 BRST 2015
Executing Ping... Fri Feb 06 14:46:04 BRST 2015
Executing Ping... Fri Feb 06 14:46:04 BRST 2015
Executing scheduler, 3 jobs found. Fri Feb 06 14:46:04 BRST 2015
Executing Ping... Fri Feb 06 14:46:04 BRST 2015
Executing Ping... Fri Feb 06 14:46:05 BRST 2015
Executing Ping... Fri Feb 06 14:46:05 BRST 2015

**Comment by jbrisbin** [comment]
Not sure if it's related but it logs that it found 4 jobs right before going into the pause. It only found 3 all other times. Why is that time different?

**Comment by leosilvadev** [comment]
Anyway, I'll download and update the version manually to see if there's some difference, if it has I'll try to update the dependency here in the process.

**Comment by jbrisbin** [comment]
If you have access to a profiler, it should be relatively easy to determine what is holding up the ring buffer thread and causing the pause.

**Comment by leosilvadev** [comment]
I updated the version to 2.0 build snapshot and now it works ok.
But now I will start to profiling the application trying to find out the exactly problem.
Should I close the Issue?
