### ISSUE TITLE
Update PersistentQueue to work as expected with the new Chronicle constraints

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor#433]
Since Chronicle now checks for barriers before writing (who wrote first, is the current thread the same one that started writing ?), we need to make sure we hide that complication to the end user.
Esp. it breaks QueueChannel reactor backed feature in SI !

**Comment by artembilan** [comment]
The SI linked issue: https://jira.spring.io/browse/INT-3644

**Comment by artembilan** [comment]
Guys, I see `2.0.0.RELEASE` is behind the door already.
Can you confirm that this issue has been fixed, too ?

Or when are you going to address it.
See the linked SI issue

Thanks

**Comment by smaldini** [comment]
Depend on how we deal with it. I think there is also a case to see if using a dispatcher in the test itself on in the front might also be required unless we do the async handoff ourself (as a single thread ever can write to the latest chronicle map).

**Comment by smaldini** [comment]
We will augment the Spec with dispatcher options and default to small dedicated ringBufferDispatcher by default.

**Comment by smaldini** [comment]
Should be fixed by https://github.com/reactor/reactor/commit/cdd270998dbfea4e859af0105b2fcc61fd3795d0 - please let me know and I'l re-open if required.
