### ISSUE TITLE
RandomFilter should use ThreadLocalRandom

### ISSUE THREAD

**Issue by thomasdarimont** [reactor/reactor#434]
`RandomFiler` currently uses a plain Random - we should rather use a `ThreadLocalRandom` here:
https://github.com/reactor/reactor/blob/master/reactor-core/src/main/java/reactor/bus/filter/RandomFilter.java#L31

**Comment by jbrisbin** [comment]
Originally we targeted JDK 6 so we went with the plain `Random`. Now that we're on 2.0, I think we can go with a minimum of JDK 7. We haven't made any "official" move in that direction yet as I think we've tried to make it as JDK 6 friendly as possible.
