### ISSUE TITLE
Make Event an interface

### ISSUE THREAD

**Issue by ifesdjeen** [reactor/reactor#435]
Hi,

Would it be possible to make Event an interface before the next Major release?

Current `Event` can become `EventImpl` or something else. That could have many use-cases, help with packaging and hiding Reactor behind a custom API (for when the lib is handling Event passing differently or has to abstract it). Also, things such as immutable events would be possible. Clojure wrapper could even have atomic events with very small effort.

What do you think? :)

**Comment by jbrisbin** [comment]
I would prefer a "real" name like `BasicEvent` or `ThreadSafeEvent` or something descriptive. I've never been a fan of *Impl. ;)

I'm not opposed to this and can't see any reason not to pursue this. We might have to change `Event.wrap()` to `Events.wrap()` or similar, which would mean a breaking change, of course. But the benefits seem worth it, if @ifesdjeen thinks they are.

I'm by myself this week, and we've got a lot of irons in the fire. Post 2.0 we'll have to see how it goes but I may have to say what all users of an OSS library hate to hear: "we're happy to accept a PR". ;)

**Comment by ifesdjeen** [comment]
Impl thing was just an example :) i didn't intend to actually name it this way.

@jbrisbin if we could still jam it into 2.0 release (since it's a breaking change), I could work on the Pull Request, if you generally agree with the idea and think it may get accepted.

**Comment by smaldini** [comment]
Since we're moving towards typed Processors (http://projectreactor.io/docs/reference/#core-processor)  that will be part of the next release (2.0.2.RELEASE now)
