### ISSUE TITLE
2.0.0.RC1 severe object/memory leak in eventBus, mostly impacting groovy users

### ISSUE THREAD

**Issue by achichenin** [reactor/reactor#443]
In eventBus implementation (i'm testing this with groovy) it is possible to use eventBus.send method with following parameters: 

``` groovy
Object key, T obj, Closure handler
```

which can lead to code like:

``` groovy

// Using cycle here to illustrate the simpiest way of reproducing the issue.
// The point here is to call same event with same result handler multiple times
for (i in (1..10000)) {
   eventBus.send("key", i) {
       // and this is consumer closure
       // instance of this closure will be created on each iteration
       // this is also a groovy issue, as it should not create new closure 
       // instances if no external objects are referenced, but this is side issue
   }
}
```

As far as I understand the problem lays on the fact that under the hood reactor creates `Consumer` for each `eventBus.send` and subscribes it to anonymous selector. Consumer object is never be de-referencied, and so Consumer/Closure. 

Of course, we can resolve this by only creating closure or consumer once, and in this case reactor propery re-use this consumer and will not leak:

``` groovy
def consumer = {
    // This will be created only once
}

for (i in (1..10000)) {
   eventBus.send("key", i, consumer) 
}
```

But, of course, it will still leak slightly if it will be implemented as a function, because new closure still will be created per each function call and never de-referencied.

I assume similar will happen in java with Observable or sendAndReceive with consumer object. In groovy it is just too counter-intuitive and in applciations with a lot of events occuring slowly it will be hard to notice and debug.

**Comment by smaldini** [comment]
That's a critical issue, we lost our attention on the event bus a bit the time being we were implementing Stream but I'll make sure that is fixed. In theory they should be one-time consumers (the reply to) and be unregistered as soon as they have been used.

**Comment by achichenin** [comment]
Hi, Stephane!

So after some more profiling I can confirm that we can use:
```
      eventBus.sendAndReceive("key", Event.wrap(i)) {
                   // actions
            }
```
due to the fact that it currently handles this particular case properly: 
```
	public <T extends Event<?>> EventBus sendAndReceive(Object key, Event<?> event, Consumer<T> reply) {
		Selector sel = Selectors.anonymous();
		on(sel, new SingleUseConsumer<T>(reply)).cancelAfterUse();
		notify(key, event.setReplyTo(sel.getObject()));
		return this;
	}
```
I'm not understand that I understand all the complexity with `SingleUseConsumer` on the inside, but it works pretty good.

I still think, that groovy wrapper for send should be fixed, probably by making `ClosureEventConsumer` to implement`SingleUseConsumer` insted of `Consumer`. 

But in general  `send` and `sendAndReceive` seems to be a little redundant and confusing, especially in groovy.

Also, thanks for all the hard work on this project and supporting Grails 3 already!

**Comment by achichenin** [comment]
And one another thing: 
In some cases it's necessary to be able to process replies from multiple consumers, but SingleUseConsumer will cancel after the first event.

In theory, we can use some sort of latch, and cancel subscription after receiving all replies (possibly combining them), With ThreadPool we will also need to synchronize this latch.

Should we just try to avoid eventBus for such cases altogether and somehow use Streams?

**Comment by smaldini** [comment]
Yes this is is typically falling off in Stream category, in a nutshell the EventBus is for 1-level complexity and ultimate routing flexibility where Stream is N level complexity with pre-determined routing (often 1-1 but supports 1-N and N-1 and groupBy).

**Comment by jbrisbin** [comment]
We've talked about providing a dedicated fork/join abstraction that uses `Stream` since it's such a common use case but we've not had time to implement it. It essentially involves creating a `Stream` from your closure/runnable and calling `.dispatchOn(Dispatcher).consume(r -> r.run())`

**Comment by jbrisbin** [comment]
@smaldini correct me if I'm wrong, but this is about all you need to do fork/join:

```java

	@Test
	public void forkJoinPool() throws InterruptedException {
		CountDownLatch latch = new CountDownLatch(3);

		ForkJoin.join(
				() -> 1,
				() -> 2,
				() -> 3
		).consume(nums -> nums.forEach(i -> latch.countDown()));
		
		assertThat("Latch was counted down", latch.await(1,TimeUnit.SECONDS));
	}

	static class ForkJoin {
		static <T> Stream<List<T>> join(Callable<T>... tasks) {
			List<Stream<T>> streams = new ArrayList<>(tasks.length);
			for (Callable<T> task : tasks) {
				streams.add(Streams.just(task)
				                   .dispatchOn(Environment.cachedDispatcher())
				                   .map(c -> {
					                   try {
						                   return c.call();
					                   } catch (Exception e) {
						                   throw new IllegalStateException(e);
					                   }
				                   }));
			}
			return Streams.join(streams);
		}
	}
```

**Comment by smaldini** [comment]
Yup however you assume here that you want to join in an array ?
If you want interleaved single items merge, just use Streams.merge, and for custom strategy, zip.
