### ISSUE TITLE
Consumers not being notified

### ISSUE THREAD

**Issue by mburak** [reactor/reactor#444]
Basically I'm working on a grails application using reactor-core and reactor-spring 2.0.0.RC1. I'm sending events to an eventbus (notify) on GORM events (similar to GormReactorBridge on events plugin). 
The problem is when i sent events from a thread (not the main one) the consumers are not notified until I've got a flush on the main thread that launches the pending events. 
I can't understand why this is happening.... any idea?

**Comment by mburak** [comment]
John, I saw you made changes to fix that, but you did that on an older version of reactor-core? I'm getting this issue on 2.0.0.RC1.

**Comment by jbrisbin** [comment]
I don't think this issue is related to that fix since the MultiThreadDispatcher class in the 2.0 branch doesn't do recursive dispatching at all so the same fix can't be applied.

What `Dispatcher` have you assigned to the `EventBus`?

**Comment by mburak** [comment]
I’m using RingBufferDispatcher. It seems that a some point the dispatcher gets stuck. Events are added to the reactor but the listeners never get them.

**Comment by jbrisbin** [comment]
> It seems that a some point the dispatcher gets stuck.

This usually means something is blocking the `RingBuffer` thread or preventing it from publishing events. There's no indefinite `Future.get()` type task being done in the `RingBuffer` is there?

**Comment by mburak** [comment]
I didn’t get that question. I have some Future.get() tasks but what do you mean them to be indefinite? They should be always reached at the end of the task.

**Comment by jbrisbin** [comment]
You can't do any `Future.get()` tasks in the shared `RingBuffer` thread, as it completely locks up the `RingBuffer`. If you need to do blocking like that, then you should be using either a `ThreadPoolExecutorDispatcher` or the `SynchronousDispatcher` and letting the event notification happen in the database driver worker thread.

**Comment by mburak** [comment]
Ok, I have two questions about this:
- Could it be fine to have 2 reactors, one for GORM related events with RingBufferDispatcher and another for Futuge.get() tasks related stuff (actually they are Promises but I guess it’s the same) with a ThreadPoolExecutorDispatcher. I can’t use SynchronousDispatcher because I need tasks to be async.
- Why after doing the Promise.get() the locked events in the RingBufferDispatcher are not released and dispatched?

**Comment by jbrisbin** [comment]
You could have 2 `EventBus` instances but that seems overly complicated. Here's an example of using an `EventBus` and submitting a job to an `ExecutorService` to get `Future` blocking and event notification working:

```java
static {
	Environment.initializeIfEmpty().assignErrorJournal();
}

@Test
public void futureTest() throws InterruptedException {
	EventBus bus = EventBus.create(Environment.get(), Environment.sharedDispatcher());

	bus.on($("hello"),
	       (Event<String> ev) -> System.out.println("recv'd " + ev.getData() + " on " + Thread.currentThread()));

	ExecutorService x = Executors.newCachedThreadPool();

	bus.notify(Streams.from(x.submit(() -> Thread.currentThread().getName())), "hello");

	Thread.sleep(500);
}
```

The `RingBuffer` is for processing non-blocking events in an ordered and efficient way. There's no real benefit to using it to dispatch blocking tasks.

What kind of tasks are being executed that require blocking on a `Promise` rather than using a `Stream` pipeline?

**Comment by mburak** [comment]
On a controller I have this kind of task:

Promise p = task {
	//do some stuff that needs to be returned before continue
}
def result = p.get()

This is using ReactorPromise that adds this to eventBus. I’m decorating this Promise task with some stuff that I need (security, transactions, retries).

**Comment by jbrisbin** [comment]
@smaldini I'm wondering if we can't update the `task{}` to use a `Stream` + `.dispatchOn` to make this better?

**Comment by jbrisbin** [comment]
@smaldini @graemerocher I think this [1] should be using a `cachedDispatcher` by default rather than the shared one, given most people will probably use a blocking `.get()` in a controller.

[1] - https://github.com/grails/grails-core/blob/master/grails-async/src/main/groovy/org/grails/async/factory/reactor/ReactorPromise.groovy#L41

**Comment by graemerocher** [comment]
ok updated to use cachedDispatcher

**Comment by mburak** [comment]
That change didn't solve the problem.

**Comment by graemerocher** [comment]
@jbrisbin Any ideas?

**Comment by smaldini** [comment]
Not sure I quite follow, its usually a bad idea to wait on the promise instead of producing a value at some point and pass it to the response but I might miss something.

**Comment by mburak** [comment]
How do you wait to that value to be produced on a controller? 
Adding an onComplete that doesn’t block the thread doesn’t work because sometimes the controller is done (and thread destroyed) before the onComplete is reached and the process that is done in the onComplete is lost. 
What about what @jbrisbin <https://github.com/jbrisbin> said about changing task{} to use Stream + .dispatchOn? Would that help?

**Comment by graemerocher** [comment]
Maybe if you post your controller logic we can help, usually you return the promise from the controller and let the framework create an async request for you

**Comment by mburak** [comment]
Basically I’m doing some stuff and then calling the task to create an object; if the object was not created successfully we return the object to the view in the page model, otherwise we set a message and do some logic to see where we need to redirect the user.
...

Promise p = task {
    governorService.create(governor, attributeValuesList)
}
Governor createdGovernor = (Governor) p.get()

if (!createdGovernor) {
    log.error("Error occurred saving governor record")

    Map pageModel = [
        domainTypeName          : domainTypeName,
        domainTypeID            : domainTypeID,
        attributeDefinitionsJSON: attributeValuesJSONString,
        instance                : governor,
        redirectDashboardName   : redirectDashboardName,
        instanceID              : redirectDashboardInstanceID,
        instanceClassName       : redirectDashboardInstanceClassName
    ]

    render(view: "create", model: pageModel)
}
else {
    flash.message = "${domainTypeName} ${displayAttibuteValue?.value} has been successfully created"
    if (redirectDashboardName) {
        if (redirectDashboardInstanceClassName && redirectDashboardInstanceID) {
            redirect(
                controller: 'dashboard',
                action: 'view',
                mapping: 'viewDashboard',
                params: [app: params.app ?: 'platform', dashboardName: redirectDashboardName, typeName: params.domainTypeName, instanceID: redirectDashboardInstanceID, instanceClassName: redirectDashboardInstanceClassName])
        }
        else {
            redirect(
                controller: 'dashboard',
                action: 'view',
                mapping: 'viewDashboard',
                params: [app: params.app ?: 'platform', dashboardName: redirectDashboardName, typeName: params.domainTypeName])
        }
    }
    else {
        redirect(controller: 'governor', action: 'list', mapping: 'app', params: [app: params.app ?: 'platform', typeName: domainTypeName])
    }
}

**Comment by jbrisbin** [comment]
AFAIK you have to return the Promise to indicate to the framework that an async request is happening. If you call .get(), then you're just blocking the controller thread and you're not gaining anything over calling the service directly.

**Comment by mburak** [comment]
Yes, that works great. Thanks.
But I still have some problem listening to Gorm events. 
So I’m using Reactor spring @Selector to listen to them and inside that listener method I’m creating a FutureTask that is submitted into an executor (it’s for a retry feature). That task could be throwing new Gorm events (this would execute in the executors thread). If after the executor.submit()  I don’t do a task.get() the events posted in the executor are never listened to. Doing the task.get() makes the events to be listened fine but I think that makes each event wait for that get() and execute one after another.
