### ISSUE TITLE
Void promises throw NPE on completion

### ISSUE THREAD

**Issue by lukejackson** [reactor/reactor#446]
Void promises can only be completed with null values.

Adding a `onComplete()` / `onSuccess()` / `onError()` handler to a promise which has not completed results in a stream being created to notify the consumer.

The problem here is that when the promise completes, it provides a null value to the stream which then throws the following exception:

```
java.lang.NullPointerException: Spec 2.13: Signal cannot be null
	at reactor.rx.broadcast.Broadcaster.onNext(Broadcaster.java:123)
	at reactor.rx.Promise.valueAccepted(Promise.java:663)
	at reactor.rx.Promise.completeAccepted(Promise.java:680)
	at reactor.rx.Promise.onComplete(Promise.java:572)
```

Example test case:

```java
	@Test
	public void testVoidPromiseComplete() throws Exception {
		CountDownLatch latch = new CountDownLatch(1);
		Promise<Void> promise = new Promise<>();
		promise.onComplete(v -> latch.countDown());
		promise.onComplete(); // equivalent to promise.onNext(null);
		latch.await();
	}
```

I see that `Promise<Boolean>` is used in the code, perhaps to avoid this. However in `DatagramServer`, `Promise<Void>` is used as a return value for `join()` and `leave()`.

Should these use `Promise<Boolean>` instead? And should promises be allowed to provide null values?

**Comment by lukejackson** [comment]
Also, I see the tests in `UdpServerTests` are all ignored. Are there outstanding issues with this functionality?

**Comment by lukejackson** [comment]
Raised a PR (https://github.com/reactor/reactor/pull/447) to switch to `Promise<Boolean>` and fix the tests

**Comment by jbrisbin** [comment]
We've had some discussions around `Promise<Void>` recently and some people want to have that exposed in the API. I'm generally not in favor of that for the reasons you cite but the counter argument is that a `Promise<Void>` means there will be **no** onNext calls, otherwise the spec is violated. It should be possible to complete a `Promise` without doing an `onNext` if that's the case.

**Comment by lukejackson** [comment]
I'm relatively new to promises, but my expectation was that `Promise<Void>` should work, for a few reasons:

* `CompletableFuture<Void>` is allowed, and I would expect to be able to convert to and from `CompletableFuture`.
* In Netty, `ChannelFuture` is a `Future<Void>`. I can and do convert this to `CompletableFuture<Void>`
* I expect for there to be a one-to-one mapping from a synchronous method call (which can have a void return type) to its asynchronous equivalent (which implies `Promise<Void>`). 
* In the Promise A+ spec, it states `undefined` is a legal value for a Promise to return. `undefined` in JavaScript is the return type of function which does not return a value. I think this maps quite well to `void` in Java.
> 1.3 “value” is any legal JavaScript value (including undefined, a thenable, or a promise)

Regardless of which approach is taken, if `Promise<Void>` or fulfilling a Promise with `null` is not currently supported, I think the code should fail much earlier. Specifically:

* Promise.completeAccepted() should not call `valueAccepted(null)`. I'm not sure what else it can do but throw an exception if the promise is still pending - perhaps IllegalStateException?
* Promise.valueAccepted() should throw an exception if null is passed

**Comment by lukejackson** [comment]
Using `Promise<Boolean>` instead provides a slightly confusing API. As a developer I feel I need to check the value for false, but the implementation in fact only provides a true value, using an exception to indicate failure.

Perhaps internally a `Promise<Object>` can be used, but expose it in the API as `Promise<?>`. That way the developer knows the value is unimportant. It's also the model used in Java for `ExecutorService.submit(Runnable)` (although in that case `get()` returns null, not an instance of any Object).

**Comment by smaldini** [comment]
Hey @lukejackson, the reason we don't support Null promises is because we are aligned on http://reactive-streams.org. Agree that Boolean is not that awesome, I wasn't fan myself but we wanted to respect the specification and embrace lower common denominator. For the connection handling, I think we will improve this signature for 2.1 as its not too much impacting and we are going to collect feedbacks like yours with the 2.0 GA planned around next week.

**Comment by lukejackson** [comment]
Hi Stephane

I understand that streams are primary in reactor and promises build off them, so it makes sense that null is not allowed from that standpoint. It's a shame the two specs differ in this respect.

The main learning point for me in reactor so far has been that is everything is a stream :)

The library is fantastic, while I'm still in the early days of evaluating it, I'm excited about what it has to offer. I'm looking forward to the GA. 

Thanks

Luke

On 19 Mar, 2015, at 19:07, Stephane Maldini <notifications@github.com> wrote:

Hey @lukejackson, the reason we don't support Null promises is because we are aligned on http://reactive-streams.org. Agree that Boolean is not that awesome, I wasn't fan myself but we wanted to respect the specification and embrace lower common denominator. For the connection handling, I think we will improve this signature for 2.1 as its not too much impacting and we are going to collect feedbacks like yours with the 2.0 GA planned around next week.

**Comment by smaldini** [comment]
Thank you so much Luke, that is great feedback, be sure that this is a shared concern we are actually thinking a lot about with friends (Netflix...) !

**Comment by lukejackson** [comment]
@jbrisbin regarding your comment, I see @smaldini has made some changes since 2.0.0.RC1 in https://github.com/reactor/reactor/commit/72014596f26d16374597a6ea95f708a61b7521a7 which prevents the issue I originally raised, and allows void promises to be completed without calling `onNext()`:

```groovy
  def "A void promise can be completed successfully without a value"() {
    given:
      "a void promise"
      def promise = Promises.<Void> prepare()
      Promise<Void> completedPromise
      promise.onComplete { p ->
          completedPromise = p
      }

    when:
      "the promise is completed without a value"
      promise.onComplete()

    then:
      "onComplete is called with a successful promise"
      completedPromise != null
      completedPromise.isSuccess()
  }
```

**Comment by smaldini** [comment]
Indeed :)
