### ISSUE TITLE
reactor-net-2.0.0.RELEASE:  NettyHttpChannel protocol version is wrong?

### ISSUE THREAD

**Issue by gembin** [reactor/reactor#456]
reactor-net-2.0.0.RELEASE
```java
     } else if (version.equals(HttpVersion.HTTP_1_1)) {
			return Protocol.HTTP_2_0;
    }
```
https://github.com/reactor/reactor/blob/v2.0.0.RELEASE/reactor-net/src/main/java/reactor/io/net/impl/netty/http/NettyHttpChannel.java#L72

**Comment by smaldini** [comment]
doh Thanks a lot, fixed for 2.0.1. We are in pre-GA phase actually and we are fixing a few of these things + doc for 2.0.1 which is going to be GA and announced etc, thanks a lot !
