### ISSUE TITLE
Correct Maven coordinates for Spring Reactor.

### ISSUE THREAD

**Issue by sagarrao** [reactor/reactor#457]
I had a very basic question regarding the maven co-ordinates for spring reactor. 

We want to use spring reactor and struggled a bit for finding the exact dependecny which had to be added.

The co-ordinates listed on the github link, didn't compile properly and so didn't the ones mentioned on this link:

https://spring.io/blog/2013/11/12/it-can-t-just-be-big-data-it-has-to-be-fast-data-reactor-1-0-goes-ga

Eventually, we ended up using this:

compile("org.projectreactor.spring:reactor-spring-context")

Just wanted to double check whether this is the apporpriate version or not?

**Comment by smaldini** [comment]
Best to use 2.0.2.RELEASE now on (http://projectreactor.io/docs/)
