### ISSUE TITLE
TcpServer implementation class cannot be null when using latest 2.0.1.BUILD-SNAPSHOT (24-Apr-2015)

### ISSUE THREAD

**Issue by JernejJerin** [reactor/reactor#462]
I am using the following code to instantiate a TCP server:

    TcpServer<String, String> server = NetStreams.tcpServer(
        spec -> spec
        .listen(PORT)
        .dispatcher(Environment.cachedDispatcher())
        .codec(StandardCodecs.STRING_CODEC)
    );

After updating to latest 2.0.1.BUILD-SNAPSHOT (24-Apr-2015) I get the following error:
> TcpServer implementation class cannot be null

**Comment by smaldini** [comment]
Ha after this update, netty has been made optional dependency since the reactor-net works a bit like a driver facade. If you pull zeromq or netty it will adapt the default server, just make sure your build pulls netty-all (latest stable is 4.0.27 AFAIK)

**Comment by JernejJerin** [comment]
That was it.

**Comment by smaldini** [comment]
Take care since this was very early stage and API has been slightly cleaned, have a look at the tests the update won't be painful. Build is currently in process with the new API.

**Comment by JernejJerin** [comment]
I have updated my implementation to reflect the API changes, but now I am not receiving the stream on server side from the client. This was already working prior to changes. I think that the problem lies in the following two changes I have made. Please take a look belowe. Thank you! 

I changed the following on TCP server:

    server.consume(new Consumer<ChannelStream<String, String>>() {
        @Override
        public void accept(ChannelStream<String, String> channel) {
            channel.log("channel").consume(new Consumer<String>() {
                @Override
                public void accept(String trip) {
                    trips.onNext(trip);
                }
            });
        }
    });

To this new version:

    server.start(ch -> {
        ch.consume(trip -> {
            trips.onNext(trip);
        });
        return Streams.never();
    }).await();

And on the TCP client side from the following:

    client.consumeOn(Environment.cachedDispatcher(), ch -> ch.sink(trips));

To this (btw, why do I have to now return previous channel.sink?):

    client.start(ch -> {
        ch.consumeOn(Environment.cachedDispatcher(), s -> {});
        return ch.writeWith(trips);
    });

Is this OK?

**Comment by smaldini** [comment]
```java
@Test
	public void testIssue462() throws InterruptedException {

		final CountDownLatch countDownLatch = new CountDownLatch(1);

		TcpServer<String, String> server =
				NetStreams.tcpServer(s ->
								s
										.codec(new StringCodec())
										.listen(12012)
				);

		TcpClient<String, String> client =
				NetStreams.tcpClient(s ->
								s
										.codec(new StringCodec())
										.connect("127.0.0.1", 12012)
				);

		server.start(ch -> {
			ch.log("channel").consume(trip -> {
				countDownLatch.countDown();
			});
			return Streams.never();
		}).await();

		client.start(ch ->
						ch.writeWith(Streams.just("test"))  
		);

		assertThat("countDownLatch counted down", countDownLatch.await(5, TimeUnit.SECONDS));
	}
```

**Comment by smaldini** [comment]
`To this (btw, why do I have to now return previous channel.sink?):`
Because the return value means when do you want to close (onComplete). since now the writeWith gives you a proof data has been sent and complete when everything has been sent, this will close after that.

**Comment by smaldini** [comment]
Also you don't need to consume client input btw in this test, since the server writes nothing. And also you ch.writeWith(trips) which is only populated when server receives data, which is never going to happen :)

**Comment by JernejJerin** [comment]
Thanks for example. Maybe I should have also posted the following. I am using trips Broadcast stream by sinking values into it from large csv file:

    // create a broadcaster we can sink values into
    Broadcaster<String> trips = Broadcaster.create();

    // dispatch onto a new dispatcher that is suitable for streams.
    // Instruct the stream to request the produced subscription indefinitely.
    // By consuming values we are creating a demand to the TCP server
    trips.log("trips").dispatchOn(Environment.cachedDispatcher()).consume();

    // read line by line
    while ((row = parser.parseNext()) != null) {
          // create a string from array separated by comma
          String trip = String.join(",", row);

          // sink values to trips broadcaster
          trips.onNext(trip);

          // need to sleep because it is to fast :)
         Thread.sleep(1);
     }

Now from your test case the following works, i.e. the server receives the string:

    client.start(ch -> ch.writeWith(Streams.just("test")));

But when I use my trips broadcaster I do not get any values on TCP server:

    client.start(ch -> ch.writeWith(trips));

**Comment by smaldini** [comment]
And this ?
```java
Stream<String> sink = trips.log("trips").dispatchOn(Environment.cachedDispatcher());
//....
client.start(ch -> ch.writeWith(sink));
```

**Comment by smaldini** [comment]
oh . Edit

```java
long flushCount = 1; //Tell the writer how every often it should flush the data into network
Stream<String> sink = trips.log("trips").dispatchOn(Environment.cachedDispatcher()).capacity(flushCount);
//....
client.start(ch -> ch.writeWith(sink));
```

**Comment by JernejJerin** [comment]
Now I am getting duplicates and the server does not receive immediately when the client executes trips.onNext. If you are interested, here is the [client](https://github.com/JernejJerin/TaxiManagementSystem/blob/master/src/main/java/com/jernejerin/traffic/client/TcpTaxiClient.java) and [server](https://github.com/JernejJerin/TaxiManagementSystem/blob/master/src/main/java/com/jernejerin/traffic/architectures/EDA.java) implementation that was behaving according to my needs before API changes. The behaviour in this two implementations was the following:
* client reads large csv file line by line and sinks parsed line to the server;
* server receives each of the string immediately;

I was able to successfully debug sending and receiving one by one, as the client sinked the string to the server, the server immediately caught it in the accept method. Now I am unable to reproduce this desired behaviour. Also big thank you for taking time and helping me.
