### ISSUE TITLE
How to configure thread switch listener to bind thread bound variables?

### ISSUE THREAD

**Issue by beku8** [reactor/reactor#467]
In RxJava there's a `RxJavaSchedulersHook` "plugin", to listen context switch, so I can bind my thread local variables like:

```
@Override
public Action0 onSchedule(Action0 action) { 
  //get the ThreadLocal variables.
  return () -> {
    //bind the ThreadLocal variables again.
    action.call();
  }
}
```

Is there way to do so in Reactor?

**Comment by smaldini** [comment]
This is an explicit context switch, not when the user comes from his own thread however.
If you want to do so for every data, I suppose you could do something similar using one of the 3 explicit ways to switch thread
```java
stream.dispatchOn(dispatcher).observe( data -> bindThreadLocal() ).
stream.subscribeOn(dispatcher).observe( data -> bindThreadLocal() ).
stream.process(RingBufferProcessor.create()).observe( data -> bindThreadLocal() ).
```

Otherwise if you want to do it once for a given sequence:
```java
stream.dispatchOn(dispatcher).observeSubscribe( ignore -> bindThreadLocal() ).
stream.subscribeOn(dispatcher).observeSubscribe( ignore -> bindThreadLocal() ).
stream.process(RingBufferProcessor.create()).observeSubscribe( ignore -> bindThreadLocal() ).
```

**Comment by smaldini** [comment]
I think the latter examples is happening too soon in the current release, I might be able to realign that before 2.0.2

**Comment by beku8** [comment]
What about event bus, when subscriber receives events on a different thread?
I guess I can put it into the headers before sending, and rebinding it on a receiving part, but not very elegant.

p.s where do you prefer the questions, here or stackoverflow?

**Comment by smaldini** [comment]
Questions here are totally fine, we also have a google group as well. The advantage is this is integrated with our internal chat room so we receive notifications for questions :)

So speaking about the eventBus, that's depending on the point of view simple or dumb: You just need to attach via on a delegating consumer that set the ThreadLocal.
```java
   eventBus.on($('someTopic'), event -> {
       bindLocal();
       delegateConsumer.accept(event);
   });
```
Depending on the dispatcher used behind this will ofcourse change behavior, Multi Threaded one which can concurrently call this consumer will reset the ThreadLocal for the local thread, but given that a thread busy won't dequeue further events you're fine.

**Comment by smaldini** [comment]
Note that I would rather encourage passing the information as part of the event to beat the concurrency checking performances used by the Thread Local (not as efficient as reading a local immutable object, but your mileage may vary).

**Comment by beku8** [comment]
As you pointed out, 
> Depending on the dispatcher used behind this will ofcourse change behavior ...
I think if we can hook some event listener to be called when dispatcher changes the context just like RxJava does, to me it would be very nice.
I really wish I did not have to deal with Thread Local, not even for performance reasons, every time we introduce new technology stacks, its just usually the fishy area.
Anyways thanks for the answers, hope to see reactor to become the "de facto" for reactive java apps.

**Comment by smaldini** [comment]
Yeah I see what you mean, something that is only invoked once by thread creation I suppose. I will re-open the issue as we might investigate that. As we move on, current Dispatchers are evolving to Processor as well (like their cousin RingBufferProcessor and RingBufferWorkProcessor), thus making a good fit for intercepting the scheduling with `onSubscribe`.
