### ISSUE TITLE
reactor.io.Buffer change Charset

### ISSUE THREAD

**Issue by miladjafary** [reactor/reactor#468]
Hi. @smaldini 

In the reactor.io.Buffer Charset define as a static final and UTF-8 so that it's not possible to change it to another Charset(e.g : cp1256)

How could I change it ?

**Comment by smaldini** [comment]
I wouldn't use Buffer for decoding to string but pass the buffer to a `new StringCodec(charset)` directly. The internal asString() is just an alias for toString trying to do basic stringification, but Buffer encoding/decoding should be defined with Codec (http://projectreactor.io/docs/reference/#core-codecs). Let me know if you face any issue.

**Comment by miladjafary** [comment]
Solved.

I thought that you used Buffer in sending packet in TcpClient and use UTF-8 for converting string to byte. 

Thank you for replay

**Comment by smaldini** [comment]
Thanks! We do use Buffer (still the missing part in the doc, its coming I swear :D) but we combine with Codec for any sort of byte transformation
