### ISSUE TITLE
Streams.period() and Streams.timer() fail silently.

### ISSUE THREAD

**Issue by masterav10** [reactor/reactor#469]
`Streams.period(...)` and `Streams.timer(...)` using a HashWheelTimer do not broadcast if the delay specified is less than the supported resolution.

A test case demonstrating the behavior can be found here:
https://gist.github.com/masterav10/a55299e58309c535482a

Potential solutions:
* Add an `isResolutionSupported(long, TimeUnit)` method to the Timer interface. Clients using the timer could then build the check into invariants.
* Throw an unchecked exception when registering a consumer with an invalid delay.

Tested using 2.0.1.RELEASE

**Comment by smaldini** [comment]
Good catchup, I'll fix that for 2.0.2

**Comment by smaldini** [comment]
Excellent and welcome to the contributors BTW, I'm adding your test directly in the suite if you don't mind (with credits ofc)

**Comment by smaldini** [comment]
In the latest master we went down to 50ms default resolution but regarding your test it is actually passing the error but there is no error consumer or Environment error journal (Environment.initialize().assignErrorJournal()) for default error logging. I wonder if I should set it automatically actually.

**Comment by masterav10** [comment]
The fact that HashWheelTimer specifies a resolution is an implementation detail, so I suppose exposing that via the interface would not be appropriate since not all Timer implementations will need that function.

Is there a reason why you wouldn't want to set the default error journal?

I'm in favor of the API failing at stream creation with an error rather than simply logging it.

**Comment by smaldini** [comment]
Makes sense, we do try to respect the reactive stream contract which is capturing all errors for isolating them in downstream instead of bubbling up. But there is an exception to that which we don't fully implement: Fatal exceptions. One can consider that one as a Fatal Exception :)

**Comment by masterav10** [comment]
Exactly. This is one of those rare cases where the error shouldn't propagate into the pipeline, since it really is a mistake by the programmer.

Feel free to add the test by the way.

**Comment by smaldini** [comment]
2.0.2.RELEASE is available
