### ISSUE TITLE
RingBuffer Processors rephrase documentation

### ISSUE THREAD

**Issue by beku8** [reactor/reactor#472]
On the documentation's [RingBuffer Processors](http://projectreactor.io/docs/reference/#_ringbuffer_processors) section it says 

> Replay from the latest not consumed data:
   If no Subscriber is listening, data won’t be lost (unlike Broadcaster from Reactor-Stream).

What does it mean? If message arrives & no subscriber is registered, it will still keep the message on the memory forever? Or does it mean subscriber is overflown, so it waits for it to drain?

**Comment by smaldini** [comment]
It means both as functionally it's the same issue: a message can't be delivered. If no subscriber is registered the data is kept yes. We plan to add timeout but obviously the processor fits into the ultra fast pipeline. You can configure how much you want here to sit tho (default to 32). But we wanted first to achieve zero data loss. An alternative is to use a timed drain yourself for now.

**Comment by smaldini** [comment]
This will drain every 10 sec the most recent data
```java
Streams.wrap(processor).throttle(10000).consume();
```

**Comment by beku8** [comment]
Ok so as soon as it hits 32 messages, it will start draining by FIFO order as new messages arrive? 
As an alternative, I can configure ```Broadcaster``` with ring buffer dispatcher to achieve same performance right?

**Comment by smaldini** [comment]
This will drain a message every 10s in fact, which doesn't affect anything if there is actually another subscriber faster than 1 data every 10s. 
The Broadcaster will be slightly less fast as it can't be optimized the same way (one ringbuffer for N streams vs a processor one ringbuffer for one stream). 

The choice is the following: intensive pipeline (many data) -> Processor, lots of small pipeline (like promise or a few data) -> Broadcaster+ringbuffer.

**Comment by beku8** [comment]
I'm sorry I meant the default behavior, without throttle.

**Comment by beku8** [comment]
But for the other part, I got it, thanks for the explanation

**Comment by smaldini** [comment]
for the processor it means that data is always consumed as soon as it arrives if there is a subscriber demanding it. If not they will pile up to the size of the buffer and if you keep sending at this stage you will block until someone drains the pile. So it's a bit like adaptive poll/push, when someone is here and ready, push to him, when he's not, accumulate.

**Comment by smaldini** [comment]
This way you can only overrun a consuming logic (sending to DB or whatever) only when the consumer asked for Long.MAX. You propagate your backpressure to the processor which if subscribed itself propagated it upstream or do his best which is mitigate the slowness downstream until he's full.

**Comment by beku8** [comment]
ok thanks

**Comment by smaldini** [comment]
Closing but should you have more questions we're here to help!

**Comment by beku8** [comment]
Thats great, I now have much better idea of what the back pressure is all about.

**Comment by smaldini** [comment]
I'll try to clarify that in the doc.
