### ISSUE TITLE
HashWheelTimer's Pausable does not pause.

### ISSUE THREAD

**Issue by masterav10** [reactor/reactor#473]
Calling `Pausable.pause()` does not actually pause the task sumbitted to a HashWheelTimer. Test case to demonstrate the behavior:

* https://gist.github.com/masterav10/b93c7f76ed433b3647a6

I suspect that cancel has a similar problem, although I did not try it.There may be some contention between `TimerPausable.reset()` and `TimerPausable.pause()`.

It was originally working in 2.0.0.M1 with `Registration`.

Tested using 2.0.1.RELEASE.

**Comment by smaldini** [comment]
Awesome, verifying it on my side and trying fixes. It has escaped the test suite for some reasons indeed, we use timer so much for the microbatching story that pause wasn't properly used by our own API to break the builds.

**Comment by smaldini** [comment]
2.0.2.RELEASE is available
