### ISSUE TITLE
Streams.combineLatest(Iterable, Function) fails silently

### ISSUE THREAD

**Issue by masterav10** [reactor/reactor#474]
When using the `Streams.combineLatest(Iterable, Function)` function, if the provided Iterable has only one element, all downstream elements never receive any data.

Complimentary test case:
https://gist.github.com/masterav10/8616964b629b07f6168f

I installed an errorJournal this time and did not receive any errors, so I'm not sure what's causing the problem. I've used other versions of the function, and they appear to be working.

I have not tried the other functions such as join(Iterable) or merge(Iterable), as I have not had a need to do so. I would recommend adapting the above test case to validate the behavior of those functions.

Tested using 2.0.1.RELEASE.

By the way, have I mentioned that the `Streams.combineLatest(...)` is my favorite feature that got added between 2.0.0.M1 and 2.0.1.RELEASE? 

### It's AWESOME.

**Comment by smaldini** [comment]
Testing that, was about to release 2.0.2.RELEASE with other fixes we discussed around timer (BTW there was a slight issue I've fixed with Timer.submit it was submitting the double of the delay passed).
If I can make a fix for the release I'll tell you.

**Comment by smaldini** [comment]
Don't hesitate to use .log("category.log.youwant") whenever you can to help you understand the streams  flows btw.

Also there is a .debug() available in the Control returned by consume(), if you println a toString() of this debug() object you should see interesting things.

**Comment by smaldini** [comment]
ok fixed locally, it was expecting at least 2 streams to combine.

**Comment by smaldini** [comment]
will be in 2.0.2

**Comment by smaldini** [comment]
2.0.2.RELEASE is available
