### ISSUE TITLE
Some documentation codes are invalid?

### ISSUE THREAD

**Issue by beku8** [reactor/reactor#475]
Documentation code for back pressure and overflow, states that following logic can be done with ```capacity(1).consume(...)```: 
```
Streams.range(1,1000000)
  .subscribe(new DefaultSubscriber<Long>() 
    Subscription sub;

    @Override
    void onSubscribe(Subscription sub){
      this.sub = sub;
      sub.request(1); 
    }

    @Override
    void onNext(Long n){
      httpClient.get("localhost/"+n).onSuccess(rep -> sub.request(1)); 
    }
  );
```
Also there's an example, in the Understanding threading model section:
```
Streams
		  .range(1, 100)
		  .subscribeOn(Environment.workDispatcher()) 
		  .process(RingBufferProcessor.create()) 
		  .capacity(1)
		  .consume();
```
So I tried to run the following code:
```
Streams
   .range(1, 32)
   .subscribeOn(Environment.workDispatcher())
   .process(RingBufferProcessor.create())
   .capacity(1)
   .consume(l -> {
       logger.info("arrived {}", l);
    });
```
However this only runs when the range is less than 32(evidently, the number of the available slots on the processor). Otherwise it freezes forever. Is this an expected behavior? If yes, code above is invalid?

**Comment by smaldini** [comment]
That's an optimization issue I fixed in the snapshot - 
.dispatchOn(Environment.get())
.capacity(1)
will work. This is because it ignores the capacity for synchronous dispatcher (in the example we use the processor).

Don't hesitate to add .log() to see what happens, you should see the consumer requesting Long.MAX where it should only have requested 1.

**Comment by beku8** [comment]
It works! Though I don't understand completely, hope soon will. log() is handy indeed, thanks.

**Comment by smaldini** [comment]
I leave it open since I have a bug related locally should have worked for the process too.

**Comment by smaldini** [comment]
right it will be fixed in 2.0.2.RELEASE

**Comment by smaldini** [comment]
Clarified the doc, updating.  "process()" in that case is going to run onSubscribe in the ringbuffer thread, so we need the subscribeOn to happen after to alter that subscribing thread. In the end that thread is where the consumer is going to request, either 1 by 1 with capacity(1) or with everything (Long.MAX).

**Comment by smaldini** [comment]
2.0.2.RELEASE is available
