### ISSUE TITLE
EventBus + dispatcher vs Processor + stream

### ISSUE THREAD

**Issue by beku8** [reactor/reactor#476]
I'm trying to refactor my **spring integration** based CRUD event listener workflow into **reactor**. Basically RESTful endpoints send Events wrapping the domain object, and event listeners for **_that specific**_(e.g `EventListener<Foo>` for events on `Foo` object) domain object would run asynchronously. I'm hesitant about the approach to use:
- **EventBus + Dispatcher**: Obviously simplest approach. Each event listener would be wrapped inside `eventBus.on('custom selector to filter by domain object', ev -> { call eventListener on worker thread } )` if the domain object matches, dispatch the task to a worker thread. 
  - Pros: probably uses less resource compared to the next approach; selectors would run in the single shared thread, then worker thread dispatches for only necessary event listeners.
  - Cons: no back pressure support
- **RingBufferProcessor + Stream**: `Streams.wrap(processor).filter(check if the domain object matches).consume(run the event listener)`. 
  - Pros: back pressure support.
  - Cons: On the SpringOne talk you guys mentioned, thread switching is expensive, less thread is better for the throughput. In this case, every event listener will become a subscriber to every message to come and do the filter on its own threads, I don't know how much threads ringbuffer processor allocates, just does not seem to be very scalable option?

I know this is a very vague question, are my concerns/understandings valid? Any suggestions will be highly appreciated.

**Comment by rksanket** [comment]
Any comments on this thread - as we too are concerned by this? Although with the second option we can have RingBufferWorkProcessor to avoid event listener from subscribing to every message., concerns for the first option remain one of critical items. 

Any plans or are there any technical workarounds around the first option - apart from using a combination of both.

**Comment by beku8** [comment]
I went with the 1st approach FYI.

**Comment by ifesdjeen** [comment]
If you're lacking stream feature set in `EventBus` you might want to take a short look at `pipes`. Pipes combine the "best of the two worlds": they allow you to have a constrant time dispatch plus stream-like functionality.

**Comment by smaldini** [comment]
We're working on resolving issue 1 .  A processor by iteself is used internally now in a Bus, but we share it amongst various event listeners, what we need to provide is a return type enum like ReactiveSession on notify() methods, this enum and others informations from the bus like getRequested would help a lot.

I'm also thinking about having internally a processor per event topic regardless of the number of events listeners to uncouple backpressure between different event listeners for different topics. Right now you have to use different EventBus to make sure you segregate the flows.

**Comment by smaldini** [comment]
On a more global note, I wouldn't dismiss Spring Integration necessarly and we will make everything in our power to combine the best of Reactor and Spring Integration in Spring 5 probably with a similar intent to backup  Message Channels with internal Processor (and therefore an helper sender object that support backpressure information). The biggest missing point in Reactive Streams in general IMO and also in usual Rx solutions it the support of Hot pipelines like you are describing and our intent is to make sure we assist especially for this use case too in the next Reactor and Spring.
