### ISSUE TITLE
Can i use 2 different receivers types(Reactor one is RING and another THREAD POOL) on the same app?

### ISSUE THREAD

**Issue by aviadhadida** [reactor/reactor#481]
I would like to publish event from a layer, and the handle should be with 2 diffrent types, one of them should be on RING_BUFFER becuase i have non blocking actions with high throughput and for another moudle that with blocking actions i would like to use THREAD_POOL. This thing is possible?
Thanks
Aviad

**Comment by smaldini** [comment]
Sure you can, just declare 2 different Stream with subscribeOn(RingBufferDispatcher) and subscriberOn(WorkQueueDispatcher/ThreadPoolDispatcher) (we prefer the first).
Or use the EventBus as I see you prefer this one and declare 2 distinct event bus with 2 different dispatchers then forward the event into the other.
