### ISSUE TITLE
Documentation issue (or possibly bug) around Stream.capacity 

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor#482]
According to the section on Setting Capacity:

> capacity will not affect consume actions if the current Stream dispatcher set with dispatchOn early on is a SynchronousDispatcher.INSTANCE (default if unset).

That comes along with an example:

````java
Stream<String> stream;

stream
    .dispatchOn(sharedDispatcher())
    .capacity(256) 
    .consume(s -> service.doWork(s)); 
````

However the only way I could make capacity work is to use `consumeOn` passing a dispatcher that's not the same as the default. This also confirmed by looking at the code which does this:

````java
dispatcher != getDispatcher() || PROCESSOR_SYNC == dispatcher ? getCapacity() : Long.MAX_VALUE
````

To experiment I used `Streams.createWith` in order to print the demand being requested. The following works as expected (demand of 5 is requested and after 10 items the publisher stops):

````java
Environment.initializeIfEmpty();

Stream<Object> stream = Streams.createWith(new BiConsumer<Long, SubscriberWithContext<Object, Void>>() {

	private long totalDemand = 0;

	@Override
	public void accept(Long demand, SubscriberWithContext<Object, Void> subscriber) {
		print("Requested demand=" + demand + ", Subscriber=" + subscriber);
		for (int i = 0; i < demand; i++) {
			subscriber.onNext("data");
		}
		this.totalDemand = this.totalDemand + demand;
		if (this.totalDemand >= 10) {
			subscriber.onComplete();
		}
	}
});

stream.capacity(5).consumeOn(Environment.cachedDispatcher(), System.out::println);
````

The following doesn't work (it requests Long.MAX_VALUE) but matches the example:

````java
Environment.initializeIfEmpty();

Stream<Object> stream = Streams.createWith(new BiConsumer<Long, SubscriberWithContext<Object, Void>>() {

	private long totalDemand = 0;

	@Override
	public void accept(Long demand, SubscriberWithContext<Object, Void> subscriber) {
		print("Requested demand=" + demand + ", Subscriber=" + subscriber);
		for (int i = 0; i < demand; i++) {
			subscriber.onNext("data");
		}
		this.totalDemand = this.totalDemand + demand;
		if (this.totalDemand >= 10) {
			subscriber.onComplete();
		}
	}
});

stream.dispatchOn(Environment.cachedDispatcher()).capacity(5).consume(System.out::println);
````

Not sure if this is a documentation issue or a code issue but either way seems like an issue.

**Comment by rstoyanchev** [comment]
Also later on the section on Backpressure talks about using capacity as a simpler alternative to a custom Subscriber that calls `request(n)`:

> Ultimately the Subscriber can request data one by one, limiting the inflight data to 1 all along the pipeline, and requesting once more after each successful onNext(T). The same behavior can be obtained with capacity(1).consume(...).

The example shown is even simpler:

````java
Streams.just(1,2,3,4,5)
  .buffer(3) 
  //onOverflowBuffer()
  .capacity(2) 
  .consume()
````

Again doesn't seem to work as simple as that.

**Comment by smaldini** [comment]
Good Catch, will fix in 2.0.4, I added SYNC_PROCESSOR check for that reason but only applied that to Stream.process(). If you look at this method you'll see the getDispatcher return SYNC_PROCESSOR in that case. I just need to do the same with DispatchAction.

**Comment by smaldini** [comment]
The reason behind is you don't need capacity() on blocking (Synchronous) streams in theory or when you are already in the same thread. But I realized that at least for the ones with a dispatchOn earlier in the chain it should have been different.

**Comment by jbrisbin** [comment]
Part of the issue here is that the `ReactorPublisher` that `PublisherFactory` is using doesn't actually dispatch onto a `Dispatcher` like a "real" `Stream`. You can tell this by putting the `Thread.currentThread()` into the output being logged. You'll see that the `BiConsumer.apply` is invoked on the `main` thread.

If you do a `subscribeOn` it works like you'd expect but I see a different error so I think there may be a couple things to look at more than just respecting capacity when doing a `consumeOn` with the sync `Dispatcher`.

**Comment by jbrisbin** [comment]
If I change the line @rstoyanchev mentions in his first comment to respect sending capacity into a `consumeOn` (which is every consume operation, either with or without a particular `Dispatcher`) and change the `dispatchOn` to `subscribeOn`, then everything seems to work like you'd expect. The demand is set to 5 and is requested twice to get all 10 elements.

**Comment by jbrisbin** [comment]
@rstoyanchev you can also add a .log() to the `Stream` returned from `createWith` to see more useful signal information (including the thread on which those signals are passed).

**Comment by smaldini** [comment]
I fixed that in my stash in between 2 train, likely target 2.0.4.
