### ISSUE TITLE
Small Documentation problem

### ISSUE THREAD

**Issue by gsaqui** [reactor/reactor#489]
In the readme.md it says:

```
compile 'io.projectreactor:reactor-core:$reactorVersion'
```

When it should double quotes like the following:

```
compile "io.projectreactor:reactor-core:$reactorVersion"
```

I know it's small but when I'm copying and pasting it's just something I noticed.

**Comment by jbrisbin** [comment]
Nice catch! I'll sneak in a fix on the next push.

**Comment by ifesdjeen** [comment]
fixed by @bripkens
