### ISSUE TITLE
Possible bug with request(n) after flatMap

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor#491]
The following code aims to request 1 item at a time and works as expected:
````java
Streams.createWith(new BiConsumer<Long, SubscriberWithContext<Object, Void>>() {
    private int index = 1;
    @Override
    public void accept(Long demand, SubscriberWithContext<Object, Void> subscriberContext) {
        System.out.println("Demand: " + demand);
        if (index <= 3) {
            subscriberContext.onNext(index++ + " of 3");
        }
        else {
            subscriberContext.onComplete();
        }
    }
}).map(i -> String.valueOf(i))
        .subscribe(new Subscriber<String>() {

            private Subscription subscription;

            @Override
            public void onSubscribe(Subscription s) {
                subscription = s;
                subscription.request(1);
            }

            @Override
            public void onNext(String s) {
                System.out.println(s);
                subscription.request(1);
            }

            @Override
            public void onError(Throwable t) {
                t.printStackTrace();
            }

            @Override
            public void onComplete() {
                System.out.println("Done");
            }
        });
````

The resulting output is as expected although the first demand equals 2 (is that expected?):

Demand: 2
1 of 3
Demand: 1
2 of 3
Demand: 1
3 of 3
Demand: 1
Done

When switching to flatMap however, e.g. replace `map(i -> String.valueOf(i))` with `flatMap(i -> Streams.just(String.valueOf(i)))`, the output becomes:

Demand: 9223372036854775807
1 of 3
Demand: 9223372036854775807
2 of 3
Demand: 9223372036854775807
3 of 3
Demand: 9223372036854775807
Done

Is this expected behavior? It seems like even though the subscriber is requesting backpressure, the publisher upstream gets Long.MAX_VALUE.

**Comment by rstoyanchev** [comment]
This is with 2.1.0 snapshot.

**Comment by smaldini** [comment]
Arg I feared this could happen as well, investigating.... I've already notice the double request at first, and actually that's rather good as it prefetches 5 elements (requesting 10, and only after 5 request the 5 next ones, which means overall 10 pending requests). The effect is that will avoid pause you can observe when you exactly request N every N elements. 
Anyway looking at the Long.MAX issue with flatMap.

**Comment by smaldini** [comment]
Should be fixed in the next snapshot building now.

On Fri, Jun 12, 2015 at 11:45 PM, Rossen Stoyanchev <
notifications@github.com> wrote:

> This is with 2.1.0 snapshot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactor/reactor/issues/491#issuecomment-111635013>.
>



-- 
*Stéphane*
--

**Comment by smaldini** [comment]
fix in https://github.com/reactor/reactor/commit/71b1a76157c75edede7d85b09cb5a308d0333b63
Investigating separately the initial prefetch which as I said is more of a blessing right now than a curse.
