### ISSUE TITLE
Stream.flatMap() creates a exponentially increasing demand when defining a capacity.  

### ISSUE THREAD

**Issue by nitzanvolman** [reactor/reactor#500]
consider the code below:
when commenting out  ``.capacity(batchSize)`` the ``BiConsumer`` receives exactly one call with a demand of the ``numOfItems`` - as expected. 
but when running this code with ``.capacity(batchSize)`` it seams like the ``BiConsumer`` gets called several times with a demand that grows exponentially on each subsequent request. 
My expectation is that the demand will always be less or equal to the ``batchSize``

this is probably related to [this issue](https://github.com/reactor/reactor/issues/491) but i recreated this on both 2.0.3 and on the latest 2.1.0 snapshot, which should contain the  [fix](https://github.com/reactor/reactor/commit/71b1a76157c75edede7d85b09cb5a308d0333b63)

```java
package fizbuz;

import reactor.Environment;
import reactor.rx.Streams;

import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.atomic.AtomicLong;

public class FizBuzDemandBug {


    public static void main(String[] args) {
        int numOfItems = 1024;
        int batchSize = 8;
        Environment.initializeIfEmpty();
        final Timer timer = new Timer();
        AtomicLong globalCounter = new AtomicLong();

        Streams.createWith((demand, subscriber) -> {
            System.out.println("demand is " + demand);
            if (!subscriber.isCancelled()) {
                for (int i = 0; i < demand; i++) {
                    long curr = globalCounter.incrementAndGet();
                    if (curr % 5 == 0 && curr % 3 == 0) subscriber.onNext("FizBuz \r\n");
                    else if (curr % 3 == 0) subscriber.onNext("Fiz ");
                    else if (curr % 5 == 0) subscriber.onNext("Buz ");
                    else subscriber.onNext(String.valueOf(curr) + " ");

                    if (globalCounter.get() > numOfItems) {
                        subscriber.onComplete();
                        return;
                    }
                }
            }
        })
        .flatMap((s) -> Streams.create((sub) -> {
            timer.schedule(
                    new TimerTask() {
                        @Override
                        public void run() {
                            sub.onNext(s);
                        }
                    }, 10);
        }))
        .capacity(batchSize)
//                .observe(System.out::print)
        .consume(numOfItems)
        ;


    }

}
```

output:
```
demand is 8
demand is 64
demand is 576
demand is 5184

```

**Comment by smaldini** [comment]
it seems to be due to the fact the flatMap is never cleared. You might want to add sub.onComplete in your TimerTask, otherwise it keeps merging stuff but never completes. The more there are subscribers pending completion the more the demand increase to give a chance to all pending subscribers to get info. However it doesn't mean its right, but there is no chance to get even distribution upstream if we don't ask for N downstream demand x M merged subscribers.

**Comment by smaldini** [comment]
I'm testing if there are any regression anyway by forcing passing demand N upstream.

**Comment by nitzanvolman** [comment]
The above example is a sanitised version of proprietary code i cannot share, calling sub.onComplete on the example caused the demand to be more predictable, but the original code (which makes a network call and DOES call onComplete after the answer was given) still exhibits exaggerated demand.  
will test this again once cce4a12 becomes available as in a SNAPSHOT build.

**Comment by smaldini** [comment]
It's in snapshot now :) If you can give a try let me know. Re-opening then (auto closed by commit).

**Comment by nitzanvolman** [comment]
The latest snapshot is reactor-2.1.0.BUILD-20150703.170145-1.jar as for as i can see, which does not contain your latest commit.

**Comment by smaldini** [comment]
Mhh should be in the repo now http://repo.spring.io/snapshot/io/projectreactor/reactor-stream/2.1.0.BUILD-SNAPSHOT/

**Comment by nitzanvolman** [comment]
I can confirm that this fixed the issue for me. 
Is this planned for 2.0.4 or 2.1.0? and when do you expect this to be released?

**Comment by smaldini** [comment]
2.0.4, planned on maven central today, it's already in repo.spring.io tho!
