### ISSUE TITLE
How to config reactor in XML based configuration

### ISSUE THREAD

**Issue by jingxiang** [reactor/reactor#504]
We can config Reactor in spring like this:

    @Configurable
    @EnableReactor
    public class ReactorConfig {
    
    	@Bean(name = "reactor", autowire = Autowire.BY_NAME)
    	public Reactor reactor(Environment env) {
    		return Reactors.reactor().env(env).get();
    	}
    }

I try to config Reactor in xml like this:

    public class ReactorConfig {

    	 public static Reactor init() {
    		 return Reactors.reactor().env(new Environment()).get();
    	 }
    }
	
	<bean id="reactor" class="com.kalman.reactor.ReactorConfig" factory-method="init" />

As you know,the reactor is init successful, but @Consumer cant working again.... I know @Consumer need register by ReactorBeanDefinitionRegistrar with @EnableReactor

So,how can i config the reactor object in XML and also support @Consumer annotation?

**Comment by jbrisbin** [comment]
You could try not using the `@EnableReactor` and just using some of the `FactoryBean` implementations [1] directly, or by creating versions of them for your own use case and putting those in a base `@Configuration` class.

[1] - https://github.com/reactor/reactor-spring/tree/master/reactor-spring-core/src/main/java/reactor/spring/factory

**Comment by jingxiang** [comment]
thanks jbrisbin. Can you show an example?

**Comment by jingxiang** [comment]
@jbrisbin can you show me any samples?thanks very much...
