### ISSUE TITLE
2.0.4.RELEASE is not available in Maven Central Repository

### ISSUE THREAD

**Issue by sanjoykr** [reactor/reactor#507]
2.0.4.RELEASE is not available in Maven Central Repository http://search.maven.org/#browse%7C-1181463382

Does anyone know when this will be available?

**Comment by smaldini** [comment]
Damn, sync have failed then, we had issues with bintray, will be able to
fix tonight hopefully

On Tuesday, July 28, 2015, sanjoykr <notifications@github.com> wrote:

> 2.0.4.RELEASE is not available in Maven Central Repository
> http://search.maven.org/#browse%7C-1181463382
>
> Does anyone know when this will be available?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactor/reactor/issues/507>.
>


-- 
*Stéphane*
--

**Comment by smaldini** [comment]
Actually its org.projectreactor (reactor 1.x),
Reactor 2.x and onwards is http://search.maven.org/#search%7Cga%7C1%7Cio.projectreactor

**Comment by sanjoykr** [comment]
Thanks.
