### ISSUE TITLE
NetStreams.httpClient onComplete logic

### ISSUE THREAD

**Issue by z0mb1ek** [reactor/reactor#509]
Hi. I cannot understand why should I us onComplete() in http client to push some data? I thought I can use stream and push data gradually, but I can not

        Publisher<String> p = s -> {
            s.onSubscribe(new Subscription() {
                @Override
                public void request(long n) {
                    System.out.println("TestReactorWs.request " + n);
                    new Thread() {
                        @Override
                        public void run() {
                            System.out.println(1);
                            s.onNext("1");
                            try {
                                Thread.sleep(2000);
                            } catch (InterruptedException e) {
                                e.printStackTrace();
                            }
                            System.out.println(2);
                            s.onNext("2");
                            try {
                                Thread.sleep(2000);
                            } catch (InterruptedException e) {
                                e.printStackTrace();
                            }
                            System.out.println("c");
                            s.onComplete();
                        }
                    }.start();
                    System.out.println("TestReactorWs.request end");
                }

                @Override
                public void cancel() {
                    System.out.println("TestReactorWs.cancel");
                }
            });
        };

        NetStreams.
                <String, String>httpClient(
                        spec -> spec
                                .codec(StandardCodecs.STRING_CODEC)
                                .connect("localhost", 3000)
                )
                .ws("/", c -> {
                    return c.writeWith(p);
                })
                .await();

**Comment by smaldini** [comment]
for batch flushing actually. but feel free to use c.writeWith(someStream.capacity(1)) to return a a Stream that will instruct a push every 1 element.

Or alternatively someStream.flatMap( c.writeWith(p) ).consume(afterFlushConsumer)

**Comment by smaldini** [comment]
If your Publisher implements NonBlocking (isReactivePull can return false or true, it doesnt matter, but if getCapacity returns something different than Long.MAX, it will flush every capacity number).

**Comment by smaldini** [comment]
The naming will change for this actually in 2.1 to Bounded interface with a isExposedToOverflow instead of isReactivePull).

**Comment by z0mb1ek** [comment]
Big thx.
