### ISSUE TITLE
UnBoxed constructs of generic classes and methods

### ISSUE THREAD

**Issue by sirinath** [reactor/reactor#511]
Can you provide unboxed primitive versions of some of the generic classes and methods. E.g. IntStream, IntAction, IntEvent, etc.

**Comment by sirinath** [comment]
To be used with the ring buffer you will require your own mutable primitive wrapper objects.

**Comment by smaldini** [comment]
I feel like it should be a work to study in correlation with JDK8. However I am facing an issue with the pre-allocated RingBuffer internal factory right now and I will have to open it anyway to external API. E.g. RingBuffer could accept a Supplier<Signal> (implemented by default by the core processors but overridable to change the actual state stored and improve the padding in primitive case).

**Comment by sirinath** [comment]
You need something like: https://github.com/OpenHFT/Java-Lang/tree/master/lang/src/main/java/net/openhft/lang/values

**Comment by sirinath** [comment]
Also have a look at: http://www.objectlayout.org/

**Comment by sirinath** [comment]
Feel free to adopt BoxOnce if you can adopt it for this purpose.

**Comment by sirinath** [comment]
Since Tuples are more or less a integral part, it might be good to have specialised Tuple Streams also.
