### ISSUE TITLE
Publish and subscribe to the EventBus as Streams

### ISSUE THREAD

**Issue by sirinath** [reactor/reactor#513]
Can we have the ability to publish and subscribe from the event bus as streams.

E.g.

```
EventBus bus = EventBus.create(Environment.get()); 

Stream<String> stream1 = ...

Stream<String> stream2 = bus.on($("topic")); 

Stream<String> stream3 = ...
Stream<String> stream4 = ...

Stream<String> stream5 = bus.on($("topic2")); 

bus.stream("topic", stream1, stream3).stream("topic2", stream4); 

// Alternatively:
bus.to("topic", stream1, stream3).to("topic2", stream4); 
```

**Comment by sirinath** [comment]
If you do not want to do the above within the reactor-bus you can introduce a new reactor-stream-bus which extends the functionality of reactor-bus with streams.

**Comment by sirinath** [comment]
@smaldini Can you look at Stream like APIs for EventBus perhaps in a different module extending the EventBus if you do not want to have stream dependencies.

**Comment by smaldini** [comment]
Have you notice this one https://github.com/reactor/reactor/blob/master/reactor-bus/src/main/java/reactor/bus/EventBus.java#L359 ? It creates Publisher but a simple Streams.wrap(Publisher).map.... does the job .

**Comment by smaldini** [comment]
The relationship with Stream and RS will be more clear when Dispatcher will be fully replaced by Processor or another RS artefact too. Eventing doesn't benefit from backpressure now and its a core concern amongst our initial users which want to transition to backpressure ready event-driven pipelines.

**Comment by smaldini** [comment]
Otherwise I was thinking about a "provided" dependency. In bus a provided dep on stream means that we can add a new static factory like EventStreams to achieve what you wish.

**Comment by sirinath** [comment]
Having EventBus backbreasure ready should be a benefit.

**Comment by sirinath** [comment]
Wondering if you can use an object pool for Events in the bus?
