### ISSUE TITLE
Add Ambiguous / Select / Alternative function to Streams

### ISSUE THREAD

**Issue by sirinath** [reactor/reactor#521]
- Rx ref: http://reactivex.io/documentation/operators/amb.html
 - GPars Alternative: http://www.gpars.org/guide/guide/GroovyCSP.html, Select: http://www.gpars.org/guide/guide/dataflow.html#dataflow_selects

**Comment by ifesdjeen** [comment]
In my opinion, this one is also not very descriptive. Please add more info.

**Comment by sirinath** [comment]
If you have multiple streams get the nth item from each stream which emits the nth item 1st: http://rxmarbles.com/#amb

**Comment by ifesdjeen** [comment]
At least I've tried.

**Comment by smaldini** [comment]
Working on it (Publishers.amb() and Streams.amb()), this has been requested by Spring 5 rest of the team too

**Comment by akarnokd** [comment]
[Some tips](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/PublisherAmb.java).

**Comment by smaldini** [comment]
yeah I was keen on converting the zip to PublisherZip too, its again very similar and there's no queue involved in that one.... Plus if I do take this way I need to contribute something back like the current work around the visualization for rx2 observables.
