### ISSUE TITLE
Add just(T v1, T v2, T v3, T v4, T v5, T v6, T v7, T v8, T... vrest)

### ISSUE THREAD

**Issue by sirinath** [reactor/reactor#522]

**Comment by ifesdjeen** [comment]
This issue is non-descriptive.

**Comment by sirinath** [comment]
Just stops at 8 elements. You need a variable arguments version also.

**Comment by ifesdjeen** [comment]
Still not sure what that relates to.

**Comment by ifesdjeen** [comment]
Also, I don't see a good use-case for it.

**Comment by sirinath** [comment]
If you have 9+ elements

**Comment by sirinath** [comment]
8 is a too small value for `Just`

**Comment by ifesdjeen** [comment]
Are you using it in real life? Or is it just a theoretical hypothesis? Even with tuples we never go beyond 3-4. You can do it, but I think this kind of patch should come out of necessity. 

Also, it would take less time to actually implement it than to bear the discussion.

**Comment by sirinath** [comment]
I never needed to use `just` as yet but incase. For Tuples 8 is good enough as this correspond to number of arguments. Just corresponds to: https://docs.oracle.com/javase/8/docs/api/java/util/Arrays.html#asList-T...-

**Comment by ifesdjeen** [comment]
Just do it!

**Comment by sirinath** [comment]
https://github.com/reactor/reactor/pull/532
