### ISSUE TITLE
Harmonise Concat, Zip, Just, combineLatest etc. to have consistent List / Iterable based operator

### ISSUE THREAD

**Issue by sirinath** [reactor/reactor#523]
```concat``` ```merge``` uses ```Iterable``` but many of the other operations uses ```List```. I think it is best to harmonise this to be consistent. ```Iterable``` would be better than having ```List```. Alternatively you can have both.

```
concat(Iterable<? extends org.reactivestreams.Publisher<? extends T>> mergedPublishers)
```

**Comment by smaldini** [comment]
List is an optimization in the case of merge and zip since ordering matters internally (and externally for zip). I was more keen to harmonize on List with concat too but it doesn't internally use the same stuff than merge,zip and combineLatest.

**Comment by sirinath** [comment]
OK. This is not much of an issue but neat if everything is consistent. Reconsider if internals change, but no need to spend too much time unless trivial.

**Comment by sirinath** [comment]
Is there a possibility to replace Iterable with List or Collection while list is the best option. Using Iterable seems to have make the code less elegant in some cases.

**Comment by smaldini** [comment]
If we can re-evaluate now specially since these operations are in Publishers too.
