### ISSUE TITLE
StackOverflowError at reactor.core.processor.RingBufferProcessor$RingBufferSubscription.request(RingBufferProcessor.java:631)

### ISSUE THREAD

**Issue by Sirenia** [reactor/reactor#527]
2.0.4.RELEASE(JDK1.8).I wan to send the event data to the kafak queue.when the consume is block ,it will throw StackOverflowError

here is test code 
```
Environment.initialize().assignErrorJournal();
        Processor<Integer, Integer> p = RingBufferProcessor.create("queue", 32);
        Stream<Integer> s= Streams.wrap(p);
        s.consume(i -> {
            System.out.println("2-->" + Thread.currentThread() + " data2=" + i);
            try {
                TimeUnit.MILLISECONDS.sleep(10);//mock send data to kafak
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }, Throwable::printStackTrace);
        for(int i=0;i<30;i++) {
            p.onNext(i);
        }
        s.subscribe(p);
```

**Comment by smaldini** [comment]
Mhh that's strange, spring-kafka uses a similar setup without issues, might be a regression in 2.0.4, can you quickly try 2.0.3.RELEASE ?

**Comment by Sirenia** [comment]
test in 2.0.3 is ok。
Great，ths：）

**Comment by smaldini** [comment]
Hey do you have any more context for that issue trying to release 2.0.5 asap and I can't reproduce it locally.

**Comment by smaldini** [comment]
Ignore that !

**Comment by smaldini** [comment]
Actually your stream subscribe itself (Stream.wrap(p).susbscribe(b) ). Looks ok then on 2.0.4!
