### ISSUE TITLE
Eliminate synchronized and locks

### ISSUE THREAD

**Issue by sirinath** [reactor/reactor#530]
Eliminate synchronised and locks other than in startup and shutdown.

https://github.com/reactor/reactor/search?utf8=%E2%9C%93&q=lock&type=Code
https://github.com/reactor/reactor/search?utf8=%E2%9C%93&q=synchronized&type=Code

All code paths in normal operations should be lock free, with only exception in startup and shutdown or handling rare exceptional situations.

**Comment by smaldini** [comment]
Lock is relatively not used apart from Promise. 
However synchronize is a bit more present but its presence in critical path remains "contained" and some current work to harmonize dispatcher and processor go that way too. I know two places at least where synchronized is in critical path: SerializedBroadcaster->SerializedSubscriber. but there is little choice here to make it efficient, recommendation is to not use it on high throughput dispatching, and overflowing subscription (ReactiveSubscription) which should be refactored in 2.1 as an OverflowProcessor. Although it will probably still use some form of locking I need to look at some SPMC lock-free structure around.

**Comment by sirinath** [comment]
If you need any method to be synchronised look at the Active Object pattern. Have a look at: https://github.com/LMAX-Exchange/disruptor-proxy

**Comment by smaldini** [comment]
Bunch of algorithms fixed since integrated with Reactive Streams Commons or reworked (Promise)
