### ISSUE TITLE
Concurrency bug in BatchFactorySupplier results in an NPE using EventBus

### ISSUE THREAD

**Issue by Russell-Allen** [reactor/reactor#540]
First a caveat.  Reactor is quite new to me, and thus I assumed that any exceptions were (and could still be) of my own creation.

My objective was to parse an access log.  I created an EventBus with two topics, raw-line and request.  The first processor converted a raw line into a request object and the second processor counted requests per http response code.  Simple enough.

When I ran it, I encountered NPE's as follows:

```
java.lang.NullPointerException: null
    at reactor.core.dispatch.AbstractLifecycleDispatcher.dispatch(AbstractLifecycleDispatcher.java:120) [reactor-core-2.0.4.RELEASE.jar:na]
    at reactor.bus.EventBus.notify(EventBus.java:369) [reactor-bus-2.0.4.RELEASE.jar:na]
    ...
```

After peeking at the Reactor source it seemed apparent that the task object was null, and long story short I backtracked through the Dispatcher to the BatchFactorySupplier's get() and fill() methods:

``` java
    @Override
    public T get() {
        int next = NEXT_UPD.getAndIncrement(this);
        if(next >= size) {
            fill();
            return get();
        }

        T obj = objs[next];
        // wipe this reference
        objs[next] = null;

        return obj;
    }

    protected void fill() {
        fillLock.lock();
        try {
            // check again to see if the pool was filled by another thread
            if(this.next >= size) {
                for(int i = 0; i < size; i++) {
                    objs[i] = factory.get();
                }
                NEXT_UPD.set(this, 0);
            }
        } finally {
            fillLock.unlock();
        }
    }
```

The get() method does not prevent two threads from having the same next value.  Thread A may receive next = 1, while thread B gets next > size, calls fill() and resets next, then in recursive get() call thread B gets next = 1.  Now thread A and B race to read objs at next before the other clears it.

The following is a self contained test case that demonstrates the ability to get a null value back from the Supplier (which I infer is contrary to it's expected behavior.)

``` java
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

import reactor.core.alloc.factory.BatchFactorySupplier;

public class TestBatchFactorySupplier {

    public static void main(String[] args) {

        //Create a BatchFactorySupplier<Integer> of monotonically increasing values.
        final AtomicInteger counter = new AtomicInteger(0);  
        final BatchFactorySupplier<Integer> bfs = 
                new BatchFactorySupplier<>(
                        1, 
                        () -> counter.getAndIncrement()
                );
        //Create N threads to get() a value from the Supplier
        final int threadCount = 10;
        List<Thread> demands = new ArrayList<>(threadCount);
        for(int i = 0; i < threadCount; i++) {
            demands.add(new Thread(() -> {
                int iterations = Integer.MAX_VALUE/threadCount;
                System.out.println(Thread.currentThread().getName()+" starting, doing "+iterations+" iterations");
                while (iterations-- > 0) {
                    if (bfs.get() == null) {
                        throw new IllegalStateException("BatchFactorySupplier returned null.");
                    }
                }
            }, "Thread "+i));
        }

        //Start our threads and wait for them to complete (well, wait for IllegalStateExceptions's...)
        demands.forEach(thread -> thread.start());
        demands.forEach(thread -> {try {thread.join();} catch(InterruptedException ignored) {}});
    }

}
```

I usually get an IllegalStateException within 30 seconds or so.  Of course your mileage may vary.

**Comment by dguggemos** [comment]
This bug also occurs for Spring Reactor 1.1.6. We see this bug when using the [Spring WebSocket Message Broker](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-stomp-handle-broker-relay) which internally uses Reactor 1.1.6.
In consequence web socket messages are lost because of this bug.

**Comment by dguggemos** [comment]
The problem still persists for version 2.0.7...

**Comment by markathomas** [comment]
I've seen this as well

**Comment by smaldini** [comment]
This one will be painful since it has completely been internally re-engineered and make no use of that supplier at all now. I'll look at at easy wins anyway for a possible 2.0.8, but we're busy preparing http://next.projectreactor.io and release 2.1.0.M1 (warning, wip).
