### ISSUE TITLE
Missing configuration for bounded thread pool dispatcher

### ISSUE THREAD

**Issue by cabsanchez** [reactor/reactor#544]
I couldn't find in the documentation a config setting for creating a Bounded threadpoolDispatcher. But looking into the code, there's this constructor: 

public ThreadPoolExecutorDispatcher(int poolSize,
	                                    int backlog,
	                                    String threadName,
	                                    BlockingQueue<Runnable> workQueue,
	                                    RejectedExecutionHandler rejectedExecutionHandler) 

Which received a workQueue that can be bounded. Maybe it's just not exposed in config settings...

**Comment by smaldini** [comment]
It wasn't expose but that API is deprecated so far in 2.1, you simply provide your own ExecutorService now to the RingBufferProcessor or RingBufferWorkProcessor.
