### ISSUE TITLE
range+flatMap+dispatchOn hangs

### ISSUE THREAD

**Issue by akarnokd** [reactor/reactor#549]
I'm trying to compare the RxJava 2.0 implementation with the Reactor 2.0.5 implementation in a [benchmark](https://gist.github.com/akarnokd/61fa3952d0d858d329f9) and run into some strange hang with the datastream built from reactor components. Specifically, the `rcRangeAsync` benchmark with `times=1000` hangs on my machine (i7 4790, Windows 7 x64, Java 1.8u60). No CPU activity.

```java
Streams
.range(0, times)
.flatMap(v -> Streams.range(v, 2))
.dispatchOn(Environment.cachedDispatcher())
.subscribe(...)
```

The equivalent RxJava sequence uses `observeOn`. Did I mismatch `observeOn` with `dispatchOn`?

**Comment by akarnokd** [comment]
In addition, the following code doesn't print anything:
```java
Streams.range(0, 1_000_000)
.flatMap(v -> Streams.range(v, 2))
.count()
.subscribe(Observers.create(System.out::println));
```

It's RxJava equivalent (with the same Observers.create) prints 2 000 000 as expected:

```java
Observable.range(0, 1_000_000)
.flatMap(v -> Observable.range(v, 2))
.count()
.subscribe(Observers.create(System.out::println));
```

If I remove `count()`, it prints out a few numbers and stops:
```
0
1
2
1
2
2
```

**Comment by smaldini** [comment]
I noticed a few of these cases too, let me try with snapshot. We actually have a suite of benchmark to compare with rxJava in our jmh projects too with some examples including diamond setup and non linear scenarios.

Thanks for the report btw!

**Comment by smaldini** [comment]
Btw can you try consume() vs subscribe too?

**Comment by smaldini** [comment]
I've tried this 
Streams.range(0, 1_000_000)
		  .flatMap(v -> Streams.range(v, 2))
		  .log()
		  .count()
		  .consume(System.out::println);

It indeed doesn't work because of completion issue indeed, I'll have a look in the snapshot. The example is interesting indeed since there is 1M - 6 premature completions!

**Comment by smaldini** [comment]
It was an issue with the range publisher actually. a workaround is to do:

```
flatMap(v -> v > 2 ? Streams.empty() : Streams.range(v, 2))
```

**Comment by akarnokd** [comment]
Oh, I've misread your range operator. In RxJava, the second argument is the count and here, apparently it is the end value. What I wanted is for each v return v and v + 1.

**Comment by akarnokd** [comment]
FYI, now with Streams.range(v, v + 1), all async benchmarks work and here is the comparison:

![image](https://cloud.githubusercontent.com/assets/1269832/9908567/86fae124-5c94-11e5-97bf-19fd4e159028.png)

**Comment by smaldini** [comment]
Interesting I wonder how it improved in snapshot tho, as I said I need to review it, I have been focusing on forkJoin operator and Processor work with snapshot. Can you share your benchmark class ?

**Comment by akarnokd** [comment]
https://gist.github.com/akarnokd/61fa3952d0d858d329f9 but now that I look at it again, the main reactor range emits two values for times=1, my bad.

**Comment by smaldini** [comment]
No probs its invaluable stuff you're doing, flatMap is important to keep for us so I def need to improve it, but I wish I will have time to explore less Operations and more Message Passing options - so I'll reach out to you after conf probably :+1:
