### ISSUE TITLE
Why is DispatcherSupplier being marked  Deprecated ?

### ISSUE THREAD

**Issue by beihaifeiwu** [reactor/reactor#554]

**Comment by smaldini** [comment]
It's part of the core that is achieving its transition to Reactive Streams by the next major release, alongside with a few core legacy components. However these features will still be available under their new form (which is now called ProcessorService, supplying Processors).

**Comment by beihaifeiwu** [comment]
Hi @smaldini,  when will the next major release ready ? I want to use it in my new project.

**Comment by smaldini** [comment]
Hard to tell, we work hard on it tho, migration path (which is no-brainer once you have the new factory method names in mind :)) will be documented ASAP on http://next.projectreactor.io
