### ISSUE TITLE
MergeAction performs stream concat and not merge?

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor#559]
When 'merge' is used to merge to two streams and the number of elements in the first stream is greater than the demand requested, or when when the demand is Long.MAX_VALUE, only values from the first stream appear in the merged stream.  I'd expect this with 'concat' but not with merge.

In the example below, all values from the first stream 'pub1' are printed sequentially, but no values from the second stream 'pub2' are ever output.
```java
        Publisher<String> pub1 = Streams.period(1).map(l -> l + "a");
        Publisher<String> pub2 = Streams.period(1).map(l -> l + "b");
        Streams.merge(pub1, pub2).observe(s -> System.out.println(s)).consume();
```
This is reproducible in master branch.

Related to this, surely the upstream request to each publisher should be ```elements/arraySize``` and not ```elements```?

**Comment by smaldini** [comment]
Long.MAX cannot be divided so it will be unbounded for everyone, however it is expected for asynchronous streams like periodic to be interleaved. Let me look at that with the latest impl.

**Comment by dfeist** [comment]
Understood Long.MAX implies push and so unbounded and the overflow this implies is to be expected.

But IMO if you use ```consume(10)``` then on termination 5 items should have been requested from each merged stream (which could be external/persistent) rather than consuming 10 from each, and having 10 items leftover in an in-memory buffer which will then be lost.

**Comment by smaldini** [comment]
It's clearly an issue indeed (with starvation to keep in mind), it used to be dividing, somehow there's a missing test for this as CI have been quiet about that.

**Comment by dfeist** [comment]
Worth creating a separate issue for this?

**Comment by smaldini** [comment]
Fixed in master
