### ISSUE TITLE
reactor-logback: JVM stops before all events are processed

### ISSUE THREAD

**Issue by nicoulaj** [reactor/reactor#562]
`AsyncAppender.stop()` does not blocking wait before all events are actually processed. In a real application, this means all pending logs are lost when the application stops, even if stop() is explicitely called.

It would be nice to make stop() ensure all logs have been processed, or at least provide a way to do so.

**Comment by smaldini** [comment]
I'll check why the stop doesn't wait, in theory the threads are non daemon and should prevent the JVM to exit until the internal Processor onComplete().
