### ISSUE TITLE
PublishOn/DispatchOn high CPU usage

### ISSUE THREAD

**Issue by akarnokd** [reactor/reactor#564]
I'm trying to benchmark similar concepts in Reactive-Streams enabled libraries. Correct me if I'm wrong, but I've tried converting the following RxJava sequences into Reactor:

```java
Observable.range(1, 1000)
    .observeOn(Schedulers.from(singleThread1));

Observable.range(1, 1000)
   .subscribeOn(Schedulers.from(singleThread1))
   .observeOn(Schedulers.from(singleThread2));
```

and came up with the following:

```java
ProcessorGroup<Object> g1 = Processors.asyncGroup("reactor", 128, 1);
ProcessorGroup<Object> g2 = Processors.asyncGroup("reactor", 128, 1);

Streams.range(1, 1000).dispatchOn(g1);
Streams.range(1, 1000).publishOn(g1).dispatchOn(g2);
```

However, when I observe these Reactor streams, my CPU (i7 4790) usage (and kernel usage) goes up to 100% and I get results with very high error degree.

Am I using the wrong Reactor operators?

(I'm using ```compile 'io.projectreactor:reactor-stream:2.1.0.BUILD-SNAPSHOT'```.)

**Comment by smaldini** [comment]
I wonder if that is linked to the creation of multiple timers, I haven't fixed that yet. Try in the setup Timers.global(), I suspect it creates many anonymous timers (used to clean up groups).

An alternative is to use a dedicated processor :

Streams.range(1, 1000).process(Processors.topic());

**Comment by smaldini** [comment]
Also to be sure about the group behavior you could try additionally :

```java
Streams.convert(Observable.range(1, 1000).publishOn(g1).dispatchOn(g2);
```

**Comment by akarnokd** [comment]
The long asnycGroup worked. Here are the results:

![image](https://cloud.githubusercontent.com/assets/1269832/10792464/1585fdb6-7d8d-11e5-8b26-7fb02869902c.png)

The `times==1` is quite interesting with Reactor. Is there a particular optimization involved?

**Comment by smaldini** [comment]
To be honest not particularly I do wonder why, maybe a case of ValuePublisher less rigourus ? The scalar alternative to us is Supplier but so far I don't see why would that be That different, there must be an extra check we don't do and the ValuePublisher in Rx does ?

**Comment by smaldini** [comment]
I think we also use the scalaFlatMap equivalent I suppose, which allows .flatMap() to be overriden by SingleValueStream.

**Comment by smaldini** [comment]
Ah and if you can publish the benchmark I'll try to evaluate the slowness of Range which is going to move over reactor-core and follows the same treatment than FlatMapOperator to optimize things.

**Comment by akarnokd** [comment]
I've been fiddling with the idea to create a common repository of `Publisher` implementations that both RxJava and Reactor can import. I only see conflicts where the underlying scheduling or queuing system would sneak in, such as in your `flatMap` implementation.

**Comment by smaldini** [comment]
Yeah that's the thing, problem of FlatMap is its so resources consuming as we observed if not implemented with really low level tricks that makes it hard to generify the concept of message passing. The idea of reactor-core is to provide a limited suite of operators and publishers/processor/subscribers factories, alongside simple IO factories, so we made "scheduling" fit into the notion of Processor we expanded a bit to support pooling. However reactor-stream needs to be aligned to not overlap with RxJava too much so a common repo would be interesting even if we shadow it for convenience reason build time would still be able to pull latest fixes. Maybe until better solution we deal with the core stuff overlap (scheduling and flatMap) but we can work on a Publishers library for the rest ?

**Comment by akarnokd** [comment]
You know flatMap, do you think we could abstract away the queue interaction stuff and either run flatMap with a JCTools queue or any other queue Reactor uses?

**I'd be interested in an autonomous Publishers library**, provided it won't take weeks or months to release a bugfix or performance improvement.

We can share a couple of data sources and transforms (untimed):

  - just, range, fromIterable, fromArray, fromFuture, fromStream, fromCallable, 
  - defer, generate, collect, reduce, scan, sample, count, delay, delaySubscription, 
  - distinct, distinctUntilChanged, filter, ignoreElements, switchIfEmpty,
  - map, repeat, retry, onErrorResumeNext, doOnXXX, takeX, skipX, buffer, window
  - toList, toMap, toMultimap, toSortedList, withLatestFrom
  - zip (with iterable)

These require a queue:

  - flatMap, combineLatest, zip, concatMap, concatMapEager, 
  - sequenceEqual, switchMap, groupBy, publish, replay

These require a Processor:

  - retryWhen, repeatWhen, XXXSubject

The rest require either a time source or a scheduler that can delay execution of tasks.

**Comment by smaldini** [comment]
```We can share a couple of data sources and transforms (untimed):

just, range, fromIterable, fromArray, fromFuture, fromStream, fromCallable,
defer, generate, collect, reduce, scan, sample, count, delay, delaySubscription,
distinct, distinctUntilChanged, filter, ignoreElements, switchIfEmpty,
map, repeat, retry, onErrorResumeNext, doOnXXX, takeX, skipX, buffer, window
toList, toMap, toMultimap, toSortedList, withLatestFrom
zip (with iterable)```

Leaving aside the queue and processor backed operations asides for now, that list sounds spot on! I also assume it would be JDK8 min ?
Btw I'm trying to improve the latest releases in terms of perf I've detected a few hot spots I will update you if I improve anything. We should try to arrange a discussion over the next weeks offline, I'd be so much honored to speak with you actually, if you can DM me on twitter or here your contact and let me know when we can talk.

**Comment by akarnokd** [comment]
No need for Java 8 but certainly helps in implementing. Java 6 is more enabling especually due to Android users which as a shared library is worth supporting.

Drop me an email: akarnokd at gmail dot com.

**Comment by smaldini** [comment]
Still need to drop you an email, so sorry I need to close that M1 for a few dependency projects and it took time to re-align all the internal (barely finishing). I am also writing a blog post where hopefully if you're fine with it give you some credits for all your amazing take on the topic :+1:
