### ISSUE TITLE
Memory leak related to use of NettyTcpClient in Spring Framework STOMP broker relay

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor#568]
The issue was first reported in [Spring Boot #4394](https://github.com/spring-projects/spring-boot/issues/4394) using Spring Framework 4.2.2 and Reactor 2.0.6.

After some investigation there is a growing number of strong references to a couple of anonymous/inner classes in `NettyChannelHandlerBridge` on the Reactor side as well as `DefaultChannelPromise`/`VoidChannelPromise` on the Netty side.

Snapshot early on after 950 connected users:
![1](https://cloud.githubusercontent.com/assets/401908/11068395/0dc881b8-879f-11e5-8855-2d79e8d08f2a.png)

Snapshot after 30 minutes:
![2](https://cloud.githubusercontent.com/assets/401908/11068409/1ddbd80c-879f-11e5-9d73-d203b2527118.png)

It appears to be related to close + flush promises added on every write that won't clean up until the connection is closed.

**Comment by rstoyanchev** [comment]
I can confirm the fix from my tests. The snapshot remains stable at this now:
![3](https://cloud.githubusercontent.com/assets/401908/11073124/0e9c544e-87b7-11e5-880f-e2e81d5db798.png)

**Comment by smaldini** [comment]
Fixed in 2.0.7.RELEASE as per commit https://github.com/reactor/reactor/commit/552fe5860781aaa035f88f7e50428e5761739a6f
