### ISSUE TITLE
Problem migrating from Reactor 1.x to Reactor 2.x EventBus because of a missing equivalent for Reactor.notify(Object, Event, Consumer)

### ISSUE THREAD

**Issue by troinine** [reactor/reactor#570]
Reactor 1.x API had functionality to notify the associated `Reactor` with an event which triggered an onComplete callback to the provided `Consumer`. From `reactor.core.Observable`:

```
/**
 * Notify this component that an {@link Event} is ready to be processed and {@link Consumer#accept accept} {@code
 * onComplete} after dispatching.
 *
 * @param key
 *      The key to be matched by {@link Selector Selectors}
 * @param ev
 *      The {@literal Event}
 * @param onComplete
 *      The callback {@link Consumer}
 * @param <E>
 *      The type of the {@link Event}
 *
 * @return {@literal this}
 */
public <E extends Event<?>> Reactor notify(Object key, E ev, Consumer<E> onComplete)
```

We know that Reactor 2.x was meant to break the API but haven't figured an easy alternative for this functionality in the `EventBus` API. Was this functionality dropped intentionally or is there a plan to add it in the future 2.x releases? If not, what would be an alternative way to get a notification when all the registered event consumers of an `EventBus` have been notified?

**Comment by smaldini** [comment]
cc @ifesdjeen

**Comment by ifesdjeen** [comment]
@smaldini we can add onComplete notification after routing is done no problem...
