### ISSUE TITLE
Improve test support for plain Publisher

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor#579]
To test a method that returns a `Publisher` I can wrap it as `reactor.rx.Stream` turn it to `reactor.rx.Promise` and use one of the await methods. If there is  an error signal, the await methods re-throw it. This makes it difficult to tell if the error came from the method itself or from the returned Publisher. It would be much better if we could assert if there was an error signal. 

I've been experimenting with `materialize` and that works as expected on a `Stream`:
````java
Stream<Object> stream = ... ;

List<Signal<Object>> signals = stream.materialize().toList().await(5, TimeUnit.SECONDS);
Signal<Object> nextSignal = signals.get(0);
assertTrue(nextSignal.isOnError());
````

However when wrapping a `Publisher` as a `Stream`, the error signal bubbles up:
````java
Publisher<Object> publisher = Publishers.error(new IllegalStateException("boo"));

List<Signal<Object>> signals = Streams.wrap(publisher).materialize().toList().await(5, TimeUnit.SECONDS);
// the below lines are never reached
Signal<Object> nextSignal = signals.get(0);
assertTrue(nextSignal.isOnError());
````

I can get around this by applying the materialize operator before wrapping:
````java
Publisher<Object> publisher = Publishers.error(new IllegalStateException("boo"));
Publisher<Signal<Object>> signalPublisher = Publishers.lift(publisher, MaterializeOperator.INSTANCE);

List<Signal<Object>> signals = Streams.wrap(signalPublisher).toList().await(5, TimeUnit.SECONDS);
Signal<Object> nextSignal = signals.get(0);
assertTrue(nextSignal.isOnError());
````

That works but is it expected that has to be done this way? It's not intuitive that wrap + materialize doesn't work. The workaround I found is not easy to find.

There should be a straight forward way of testing a plain `Publisher` for example when working with the new `Publishers` from core.

**Comment by smaldini** [comment]
Sidenote : We are exploring this idea with https://github.com/reactor/reactor/blob/master/reactor-core/src/main/java/reactor/core/subscriber/test/TestSubscriber.java, https://github.com/reactor/reactor/blob/master/reactor-core/src/main/java/reactor/core/subscriber/test/DataTestSubscriber.java; 

Alternatively you can use Promises.from(Publisher), Publishers.toReadQueue(Publisher) and for fine grained demand testing, Streams.consumeLater() + request/cancel, consumeOnly(long n), consume (cancellable consumer). In Core and IO (Aeron in particular) we do use toReadQueue and TestSubscriber.

**Comment by smaldini** [comment]
The bubble up issue is definitively a bug tho

**Comment by smaldini** [comment]
BTW what exception is bubbling up ?

**Comment by rstoyanchev** [comment]
Strangely I think it's the original exception with a Reactor exception showing up as a cause. You can run the above code, it's self-sufficient.

Also I found another variation on this where wrapping an error Publisher:
````java
Publisher<Object> publisher = Publishers.error(new IllegalStateException("boo"));
Streams.wrap(publisher).onErrorReturn(ex -> "error");
````

The above code causes a stack trace on the second line even without any subscriber.

**Comment by smaldini** [comment]
Should be fixed in next snapshot, it was a side effect of an optimization for flatMap (considering error as scalar value but throwing exception on resolution for fast flatMap failure). It's an unnecessary optimization and I removed this behavior.

**Comment by rstoyanchev** [comment]
Looks good, thanks!

**Comment by smaldini** [comment]
Edited to reflect the issue fixed.
