### ISSUE TITLE
Option for fallback Publisher with access to Exception in ErrorOperator

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor#580]
It seems `ErrorOperator` as well as `ErrorWithValueOperator` let you either consume the error or fall back on another stream but there is no option to do both, i.e. fall back with access to the error.

The expectation is probably to work with the selector but the exception may contain useful information and there is no way to handle Throwable and decide in code (at runtime) what fallback strategy to use.

**Comment by rstoyanchev** [comment]
For comparison in RxJava, [onErrorResumeNext](http://reactivex.io/RxJava/javadoc/rx/Observable.html#onErrorResumeNext(rx.functions.Func1)) takes a function with the error as input and an Observable as the output.

**Comment by smaldini** [comment]
Good spot, it was previously reported but I can't find the ticket!
Alternatively a custom Publishers.lift could do the trick or if you feel good about it or have any spare time, a proposed operator (can start within spring-reactive and you lift it with Publishers.lift).

**Comment by rstoyanchev** [comment]
Thanks!
