### ISSUE TITLE
Provide a Rx lite API in Reactor Core

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor#584]
My proposal is to provide in Reactor Core some lighter version of `Stream` and `Promise` with the same functional scope than what there is in `Publishers`.

That would be exposed only for return types (input parameters should stay raw `Publisher`). Let's imagine we call these new types `Mono` (simple `Promise`) and `Flux` (Simple `Stream`). `Stream` could be refactored to extend `Flux` and `Promise` to extend `Mono`. 

Please see this [Spring Reactive commit](https://github.com/sdeleuze/spring-reactive/commit/transformable-publisher) for a draft API prototype.

With such simple API I am not sure keeping `Publishers` is needed. That make me think that with these changes maybe reactor-core could be eventually renamed to `reactor-stream-lite` or `reactor-rx-lite`.

Reactor API such as Reactor Net one could be updated to use these new types, for example [`ReactiveChannel`](https://github.com/reactor/reactor-io/blob/master/reactor-net/src/main/java/reactor/io/net/ReactiveChannel.java) would became:

```java
public interface ReactiveChannel<IN, OUT>  {

	InetSocketAddress remoteAddress();

	Mono<Void> writeWith(Publisher<? extends OUT> dataStream);

	Mono<Void> writeBufferWith(Publisher<? extends Buffer> dataStream);

	Flux<IN> input();

	ConsumerSpec on();

	Object delegate();
}
```
 I see no drawback (these types will still inherit from `Publisher`) and a lot of value to do that, you keep providing all Reactor Stream power, and you provide a simple API without increasing current Reactor Core scope. And this simple API will be much easier to learn for users. I think this lite Rx API would be useful for a lot of projects.

**Comment by smaldini** [comment]
Considered for experimentation in 2.1 beta process :+1:

**Comment by sdeleuze** [comment]
I have updated the proposal with `Mono` and `Flux` type names.
