### ISSUE TITLE
Reactor Next release issue

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor#600]
Reactor 2.5 is an evolution of Reactor 2.0 that makes it more modular and powerful. Initially intended to be 2.1, the new contributions from @ifesdjeen, @kadyana, @oodamien, the collaboration with Spring team and more recently with @akarnokd proved so positive that they have brought reactor to a new maturity dimension. 

For the record, Reactor provides a Reactive foundation and a lightweight / efficient Reactive Streams based composition API easy to use for applications and frameworks. It is still Java 7+ (compatible with Android 4.4+), and is sourcing its functional features from new reactive-streams-commons [1] project and reactor own implementations.

Reactor 3.0.0.RELEASE will be what Reactor 2.5 provides but built on top of Java 8+ and leverage related types like java.util.function classes.

Starting from 2.5.0.M1, Reactor is composed of the following modules, snapshots will soon reflect that change:
- https://github.com/reactor/reactor-core: reactive foundations for apps and frameworks + lite Reactive composition API with `Mono` (1 element) and `Flux` (n elements) types (originated in PR #607)
 - own documentation source : http://next.projectreactor.io/core/docs/reference
 - own API space : http://next.projectreactor.io/core/docs/api
 - clean package structure (no cycle)

- https://github.com/reactor/reactor-stream: full featured reactive composition API (Rx scope) with `Promise` and `Stream` types
 - own documentation source : http://next.projectreactor.io/stream/docs/reference
 - own API space : http://next.projectreactor.io/stream/docs/api

- https://github.com/reactor/reactor-io:
 - own documentation source : http://next.projectreactor.io/io/docs/reference
 - own API space : http://next.projectreactor.io/io/docs/api
 - reactor-aeron
 - reactor-codec: JSON, compression, Kryo, Protobuf codecs
 - reactor-net: TCP and HTTP client and server

- https://github.com/reactor/reactor-extensions:
 - own documentation source : http://next.projectreactor.io/ext/docs/reference
 - own API space : http://next.projectreactor.io/ext/docs/api
 - reactor-alloc
 - reactor-bus
 - reactor-logback
 - reactor-pylon
 - reactor-pipes

- https://github.com/reactor/reactor-incubator
 - reactor-amqp
 - reactor-chronicle
 - reactor-groovy
 - reactor-net-0mq

Each repository has its own versionning starting from 2.5.0, and incrementing to 2.5.1, 2.5.2, etc.
    
[1] https://github.com/reactor/reactive-streams-commons

**Comment by bclozel** [comment]
Indeed, a lot happened recently - thanks for sharing this initial roadmap and thoughts about the future layout. Really excited about this!

**Comment by smaldini** [comment]
Operations pending promotion review:
+Mono#then(fn1...fn8)  : currently available as Stream#forkJoin(fn1...fn8)
+Mono#filter , Flux#filter
+Flux#scan
+Flux#reduce

Operations pending JDK8 branch:
+Flux#toStream()
+Flux#toList() //uses stream collect
