### ISSUE TITLE
How do I drop old items on back pressure?

### ISSUE THREAD

**Issue by evacchi** [reactor/reactor#612]
I am evaluating the behavior of different stream processing frameworks. My problem can be described as follows:

- a producer generates values at its own rate (a hot stream)
- consumers process data on the producer stream at *their own* rate, that is, *dropping* items that the producer generated *while* the consumer was busy 
- when the producer has pushed the result on its output stream (returns the result), the next value that will be processed is the **most recent** value the consumer has produced.

It is my understanding that `onOverflowDrop()` does not do what I need because it actually *discards* incoming values. How do I make the stream drop *less recent* elements ?

Toy example that *should* micro-benchmark the event processing on drop (if I got everything right):

```java
        final Broadcaster<Long> longStream = Broadcaster.create();
       longStream.onOverflowDrop().consume(t -> System.out.println(System.nanoTime()-t));
       new Thread(()-> {
            while(true) longStream.onNext(System.nanoTime());
        }).start();
```

thanks in advance.

**Comment by smaldini** [comment]
Hi with the latest 2.5 snapshot you can use onBackpressureLatest (or onBackpressureDrop) :)
