### ISSUE TITLE
Add HTTP Cookie support to Reactor Net

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor#614]
Netty provides support for encoding and decoding cookies under `io.netty.handler.codec.http.cookie` so it should be relatively straight-forward to provide some support through `HttpChannel` and/or `HttpHeader`.

**Comment by smaldini** [comment]
Indeed I need to relate it too to the OAuth experiment in terms of UX. Note that any Reactor Channel provides for a channel.delegate() method which is the underlying Netty channel in case that helps meanwhile.

I was wondering for Spring reactive we have for now two families of runtimes, servlet and Netty, maybe this kind of adapters can be generic enough to work say over rxnetty, reactor and even ratpack or vert.x ? A lifecycle contract that may need the said Channel or Netty headers and produce that support for cookies etc.

**Comment by smaldini** [comment]
(referenced in reactor-io repository)
