### ISSUE TITLE
get rid of goldmansachs collections dependency on reactor-bus

### ISSUE THREAD

**Issue by jangalinski** [reactor/reactor#615]
Its a very uncommon library to be used as transitive dependency on an open source project ... what is so special about this lib that it cannot be replaced with the "obvious" choices commons-lang3 or guava?

**Comment by SpOOnman** [comment]
I suggest that too. I have two other reasons:
- GS Collections is used only in one class reactor.bus.registry.CachingRegistry and it uses 3 classes and 2 interfaces from it,
- GS Collections is a 8.7 MB jar so it's not justified to use jar this large for 5 entries.

**Comment by SpOOnman** [comment]
Can you explain why this issue is closed? Is GS Collections removed along with new 3.0 release? I haven't updated since June.

**Comment by smaldini** [comment]
Yes we don't use GS collection in core and we do not support yet reactor-bus with reactor 3.0, it needs a full review as design wise it is going against reactive-streams unfortunately.

**Comment by SpOOnman** [comment]
Ok, thank you!
