### ISSUE TITLE
do not expose slf4j-simple

### ISSUE THREAD

**Issue by jangalinski** [reactor/reactor#616]
the compile scope should only rely on slf4j-api. It is ok to have the simple implementation in the test scope, but it should not be a transitive dependency when I use the module.

**Comment by ifesdjeen** [comment]
Reactor has only compilation depednency, no runtime dependencies. I don't see how having compile dependency hurts. Logging implementation is determined in runtime.

**Comment by jangalinski** [comment]
you are right, sorry, misread the dependency:tree ...

**Comment by ifesdjeen** [comment]
no problem :) we do agree with you that exposing runtime dependency is generally bad practice)

**Comment by smaldini** [comment]
Is it optional or compile time :D the later being a mistake (but optional should add for IDE as compile dep)
