### ISSUE TITLE
Mono::fromFuture should accept also CompletionStage

### ISSUE THREAD

**Issue by flozano** [reactor/reactor#636]
Currently only CompletableFuture is accepted. CompletableFuture is the implementation provided in JDK8, but CompletionStage is the interoperable interface and at least one alternative implementation of it is available. All my interfaces are exposing CompletionStage instead of CompletableFuture, so it'd be great to be able to use it in Mono.

**Comment by smaldini** [comment]
Wrong repo! use https://github.com/reactor/reactor-core/issues 👍
