### ISSUE TITLE
Reactor IPC dependencies missing

### ISSUE THREAD

**Issue by robbinalexander** [reactor/reactor#643]
Dependencies under io.projectreactor.ipc like reactor-aeron, reactor-ipc are not resolved.

**Comment by smaldini** [comment]
Unfortunately Aeron and IPC are not prime time / mature ready for the BOM release train they need to be picked separately.

**Comment by robbinalexander** [comment]
Thanks @smaldini. Do you have a roadmap defined for Aeron and IPC? Do you recommend an alternative till these are prime time?

**Comment by smaldini** [comment]
Aeron doesn't depend anymore on ipc - we're still looking at updating aeron @kadyana asap

**Comment by kadyana** [comment]
@robbinalexander could you provide me with your uses cases of using Reactive Streams over Aeron?
I will check if the current implementation covers them.
