### ISSUE TITLE
Eclipse Equinox fails to install with Unresolved Requirement on sun,misc

### ISSUE THREAD

**Issue by pedrolamarao** [reactor/reactor#645]
Hello!

I'm trying to install reactor-core-3.1.1.RELEASE on Eclipse Equinox Neon.3.

Eclipse Equinox fails with the following message:

```
!ENTRY io.projectreactor.reactor-core 4 0 2017-11-23 18:51:05.885
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: io.projectreactor.reactor-core [19]
  Unresolved requirement: Import-Package: org.slf4j; version="[1.5.4,2.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: kotlin; resolution:="optional"
  Unresolved requirement: Import-Package: kotlin.collections; resolution:="optional"
  Unresolved requirement: Import-Package: kotlin.jvm; resolution:="optional"
  Unresolved requirement: Import-Package: kotlin.jvm.functions; resolution:="optional"
  Unresolved requirement: Import-Package: kotlin.jvm.internal; resolution:="optional"
  Unresolved requirement: Import-Package: kotlin.jvm.internal.markers; resolution:="optional"
  Unresolved requirement: Import-Package: kotlin.reflect; resolution:="optional"
  Unresolved requirement: Import-Package: kotlin.sequences; resolution:="optional"
  Unresolved requirement: Import-Package: sun.misc
        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1600)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

Apparently reactor-core requires sun.misc, which no OSGi implementation should export.
Is this intended?
Should sun.misc be marked as optional?

**Comment by simonbasle** [comment]
This dependency is due to our usage of `sun.misc.Unsafe`.

This blog post exposes a similar problem, albeit with Apache Camel: https://dentrassi.de/2016/07/25/camel-kura-and-osgi-struggling-with-sun-misc-unsafe/

The solution with Equinox seems to be to use a configuration property that makes Eclipse (bundle 0) delegate lookups to the boot classloader:

> **Bootclasspath delegation for Equinox**
>
> Eclipse Equinox also allows to set a few system properties in order to allow falling back to the bootclasspath and delegating the lookup of “sun.misc” to the JVM:
> 
> Also see: https://wiki.eclipse.org/Equinox_Boot_Delegation
> 
> `OSGI.COMPATIBILITY.BOOTDELEGATION=TRUE`
> This fill fall back to the bootclassloader like using the launcher “org.eclipse.equinox.launcher”
>
> **Bootclasspath delegation for all**
> 
> The OSGi core specification also allows to configure direct delegation of lookups to the boot classloader (Section 3.9.3 of the OSGi core specificion):
> 
> `ORG.OSGI.FRAMEWORK.BOOTDELEGATION=SUN.MISC.*`
> This will forward requests for “sun.misc.*” directly to the boot class loader.
