### ISSUE TITLE
How can i get the exact exception i wanted?

### ISSUE THREAD

**Issue by awakebymyself** [reactor/reactor#647]
Hi, I get a problem when dealing with the reactor3 exceptions.
 Here I just want to get the exact `MyExceotion`(print success in the console). How can I do this? I had tried some operators like `doOnError` `onErrorMap` etc.. but still can't figure out. here is hte code,  Thanks for any help  :) 
```java
public class ExceptionTest {

    public static void main(String[] args) {
        try {
            test();
        } catch (MyException e) {
            System.out.println(">>>>Success!");
        } catch (RuntimeException e) {
            System.out.println(">>>>Try again!");
        }
    }

    private static void test() {
        Mono.just(1)
                .doOnNext(integer -> {
                    throw new MyException("Test");
                })
                .subscribe();
    }

    private static class MyException extends RuntimeException {
        MyException(String message) {
            super(message);
        }
    }

}
```

**Comment by simonbasle** [comment]
Hi @awakebymyself 

As a first step I would strongly suggest to read the [reference documentation](http://projectreactor.io/docs/core/release/reference/) and learning material like those we referenced on [http://projectreactor.io/learn](http://projectreactor.io/learn).

In reactive programming, everything is asynchronous. Even error conditions are asynchronous actually, so you cannot really `try catch` around a `Flux.subscribe`.

However, when running a test or toying with the library from a `main` method, you can use `Flux#blockLast()`/`Mono#block` and that will convert the `onError` signal into `throw`ing the exception.

`doOnError` is a method that is invoked to execute some logic whenever there is an `onError` signal. It doesn't trigger the error.

One operator that creates an error signal is `Flux.error(Throwable)` (or `Mono.error(Throwable)`). There are a couple ways you could use it:

 - as a replacement for the `Mono.just(1)`: `Mono.error(new MyException("test"))`
 - as a map-to-error inside a `flatMap`: `Mono.just(1).flatMap(i -> Mono.error(new MyException("test")))`

Another way of triggering an error upon receiving a value is simply to use `map` and throw within the `map` (what you did in `doOnError`, just with the right operator).

For instance: 

```java
public class ExceptionTest {

    public static void main(String[] args) {
        try {
            test().block(); // <4>
        } catch (MyException e) {
            System.out.println(">>>>Success!");
        } catch (RuntimeException e) {
            System.out.println(">>>>Try again!");
        }
    }

    private static Mono<Integer> test() { // <1>
        return Mono.just(1)
                .map(integer -> {  // <2>
                    throw new MyException("Test");
                });
                //.subscribe(); // <3>
    }

    private static class MyException extends RuntimeException {
        MyException(String message) {
            super(message);
        }
    }

}
```
 1. we change the return type to `Mono<Integer>` and return the `Mono`
 1. we use `map`
 1. we don't subscribe anymore (that would be fire-and-forget), we'll let the `main` do that instead
 1. `main` uses the `Mono` and `block()` on it, which will convert `onError` signal into a `throw`


The even simpler version I was hinting at:

```java
    private static Mono<Integer> test() {
        return Mono.error(new MyException("Test"));
    }
```

**Comment by simonbasle** [comment]
PS @awakebymyself most of the issue activity happens on [reactor/reactor-core](https://github.com/reactor/reactor-core/issues) these days, or on our [Gitter channel](https://gitter.im/reactor/reactor?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for live discussions ;)

**Comment by awakebymyself** [comment]
@simonbasle Thank for your very detailed answer :+1:  :smiley: This is COOL !

 Besides i had solved my problem per your answer. Thanks for your help and suggestions !
