### ISSUE TITLE
ConnectableFlux does not publish events to subscribers properly

### ISSUE THREAD

**Issue by thekalinga** [reactor/reactor#648]
When I try to run this code, the second subscriber never gets events though he subscribed to `ConnectableFlux` before `connect()` is invoked

```java
  @Test
  void schedulerTest() throws InterruptedException {
    CountDownLatch latch = new CountDownLatch(2);

    ConnectableFlux<Integer> connectableFlux = just(1, 2, 3, 4, 5).publish();

    connectableFlux
        .log()
        .subscribe(v -> {} , e -> {}, latch::countDown);

    connectableFlux
        .publishOn(parallel())
        .log()
        .map(v -> v * 10)
        .publishOn(single())
        .log()
        .subscribeOn(elastic())
        .subscribe(v -> {} , e -> {}, latch::countDown);

    connectableFlux.connect();
    latch.await();
  }
```

Here is the log

```
2018-08-07 21:14:39.409  INFO 10455 --- [           main] r.F.P.1                                  : onSubscribe(FluxPublish.PublishInner)
2018-08-07 21:14:39.418  INFO 10455 --- [           main] r.F.P.1                                  : request(unbounded)
2018-08-07 21:14:41.293  INFO 10455 --- [           main] r.F.P.1                                  : onNext(1)
2018-08-07 21:14:41.294  INFO 10455 --- [           main] r.F.P.1                                  : onNext(2)
2018-08-07 21:14:41.294  INFO 10455 --- [           main] r.F.P.1                                  : onNext(3)
2018-08-07 21:14:41.295  INFO 10455 --- [           main] r.F.P.1                                  : onNext(4)
2018-08-07 21:14:41.295  INFO 10455 --- [           main] r.F.P.1                                  : onNext(5)
2018-08-07 21:14:41.296  INFO 10455 --- [           main] r.F.P.1                                  : onComplete()
2018-08-07 21:14:41.306  INFO 10455 --- [      elastic-2] r.F.P.2                                  : | onSubscribe([Fuseable] FluxPublishOn.PublishOnSubscriber)
2018-08-07 21:14:41.306  INFO 10455 --- [      elastic-2] r.F.P.3                                  : | onSubscribe([Fuseable] FluxPublishOn.PublishOnSubscriber)
2018-08-07 21:14:41.306  INFO 10455 --- [      elastic-2] r.F.P.3                                  : | request(unbounded)
2018-08-07 21:14:41.307  INFO 10455 --- [      elastic-2] r.F.P.2                                  : | request(256)
```

I'm using

`reactor-core` version `3.2.0.M3`
`Java` version `OpenJDK Runtime Environment (Zulu 8.30.0.1-linux64) (build 1.8.0_172-b01)`
`OS` version `Ubuntu 16.04.5 LTS` & `Linux idealx 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by simonbasle** [comment]
(Note: this issue should have been opened in [reactor/reactor-core](https://github.com/reactor/reactor-core/issues/) repository)

This is because the `connect()` DOESN'T actually happen before the second subscribe, due to the introduction of an asynchronous boundary with `subscribeOn`. This is made more visible if you print out the result of the connect call like so:

```java
@Test
	public void gh648() throws InterruptedException {
		CountDownLatch latch = new CountDownLatch(2);

		ConnectableFlux<Integer> connectableFlux = Flux.just(1, 2, 3, 4, 5).publish();

		connectableFlux
				.log("A")
				.subscribe(v -> {} , e -> {}, latch::countDown);

		connectableFlux
				.publishOn(parallel())
				.log("B")
				.map(v -> v * 10)
				.publishOn(single())
				.log("C")
				.subscribeOn(elastic())
				.subscribe(v -> {} , e -> {}, latch::countDown);

		System.out.println("connected with " + connectableFlux.connect());
		latch.await(5, TimeUnit.SECONDS);
	}
```

Which prints:

```
11:02:39.391 [main] INFO  A - onSubscribe(FluxPublish.PublishInner)
11:02:39.395 [main] INFO  A - request(unbounded)
11:02:39.420 [main] INFO  A - onNext(1)
11:02:39.420 [main] INFO  A - onNext(2)
11:02:39.421 [main] INFO  A - onNext(3)
11:02:39.421 [main] INFO  A - onNext(4)
11:02:39.421 [main] INFO  A - onNext(5)
11:02:39.421 [main] INFO  A - onComplete()
connected with reactor.core.publisher.FluxPublish$PublishSubscriber@7791a895   <== CONNECT HERE
11:02:39.425 [elastic-2] INFO  B - | onSubscribe([Fuseable] FluxPublishOn.PublishOnSubscriber) <== SECOND SUBSCRIBE HERE
11:02:39.425 [elastic-2] INFO  C - | onSubscribe([Fuseable] FluxPublishOn.PublishOnSubscriber)
11:02:39.425 [elastic-2] INFO  C - | request(unbounded)
11:02:39.426 [elastic-2] INFO  B - | request(256)
```

**Comment by simonbasle** [comment]
When you use `subscribeOn`, you basically say "subscribe in another thread". Would you still make the same assumption if the code read like this:

```java
new Thread(() -> connectableFlux.subscribe(...)).start();
connectableFlux.connect();
```

**Comment by thekalinga** [comment]
The analogy is not quire accurate as the call to subscribe happened on the same thread where connect is invoked. When the internal subscription happens is upto the framework

But from end user perspective he subscribed when he said `.subscribe()` for both of the subscribers

I believe the framework should keep track of who has attempted subscription & when, based on that information cache events for the slower subscribers so that the behaviour is not a surprise

**Comment by simonbasle** [comment]
Oh but using `subscribeOn(X)` **is there to tell the framework where to make the `subscribe()` call happen**.

Your argument comes from a misunderstanding of how `subscribeOn` works, it seems. It is as if you said "the runnable in that Thread line should execute in the main Thread, because the `start()` method is called from the main Thread...

**Comment by thekalinga** [comment]
Sure, I dont have complete understanding of the internals of the framework (else I would have been a developer/contributor to reactor :))

W.r.t the Runnable, the spec is quite clear that the runnable would happen sometime in the future, but the `publish()` marble diagram clearly indicates a temporal correlation between `subscribe()` & `connect()`

If the framework does not want to support what I mentioned before & is OK with this surprise & there are no guarantees (as arbitrary amount in the future is no guarantee) about whether each of the subscribers sees the upstream events, then please be explicit about it

My view is that since the indirection is introduced by the framework, the framework itself should make sure that the behaviour is consistent & there are no surprises

Thanks again for the analogy

**Comment by thekalinga** [comment]
My current understanding of of reactive streams is that it is about explicit guarantees & no grey areas, which RxJava1 did not have, but this looks like a grey area to me

**Comment by akarnokd** [comment]
> Adding non precise amount of delay is not a sufficient guarantee.

Don't use `subscribeOn` and you probably don't need `subscribeOn` as there are no subscription side effects happening when you subscribe to a quasi-hot source. Some people apply `subscribeOn` without thinking because they saw somebody doing it in some context that may not apply to the current case.

> Is there a way to be certain that all subscribe() calls prior to connect() receive all events irrespective of the boundaries as most often we need exact guarentees.

You'd have to keep peeking into the `ConnectableFlux` and see if the registered subscriber count is of the expected number. Which needs busy wait and/or sleeping for some time.

Generally, if you don't want to lose data and can't change the subscription behavior of your consumers, try using `replay()` instead of `publish()`.

**Comment by thekalinga** [comment]
@akarnokd Thanks for your reply

> You'd have to keep peeking into the ConnectableFlux and see if the registered subscriber count is of the expected number. Which needs busy wait and/or sleeping for some time.

I believe this means, I have to explicitly add an indirection to support this behaviour. Should this be done by the framework instead of me?

**Comment by akarnokd** [comment]
If you are willing to tradeoff the control over connection, you could use [`refCount(int subscriberCount)`](https://projectreactor.io/docs/core/release/api/) but otherwise yes, it is your job to implement something that is not supported by the library but technically is possible.

**Comment by simonbasle** [comment]
This is not possible without a major overhaul of the whole library's architecture, as the `subscribe()` call itself is merely propagating a signal up the chain of operators and doesn't keep track of the number of invocations, where it happened nor of the state of upstream operators. So this won't happen.

**Comment by thekalinga** [comment]
@simonbasle Thanks for the clarification. In this case, can this info be documented somewhere so that others like me might not get confused when we look at the marble diagram

**Comment by simonbasle** [comment]
The marble diagram cannot show every single corner case and combination of operators. That said, the javadoc could mention that `subscribeOn()` could make the `connect` happen before the actual subscription.
