### ISSUE TITLE
initial discussion and requirement gathering for a reactive object pool

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor#651]
We know we want one but not sure yet if it'll be a separate repo / part of addons or core. We want it to be generic though.

This issue is there to foster initial discussions around a desirable feature set for a reactive object pool project.

**Comment by davecramer** [comment]
One thing that I think is important in the cloud/container world is the ability to do circuit breaking. I know how this is done with say pgbouncer. They proxy at the protocol level. Given that you want to write a generic pool; I'm not sure how that is possible?

**Comment by smaldini** [comment]
Hey Dave, can you quickly detail how the circuit breaker operates and what it achieves with pgbouncer ?

**Comment by davecramer** [comment]
Sure.

pgbouncer has a notion of being able to PAUSE a database (note it can handle more than one database). When a database is paused any existing connections are disconnected from the database, but not the client. Any new connections will connect but not be passed through. At this point the underlying database can be turned off, upgraded, switched over (in which case pgbouncer would be reconfigured to the new IP). What this allows is for seamlessly upgrading or failing over a server., https://pgbouncer.github.io/usage.html

**Comment by rdegnan** [comment]
I saw David Moten had a pretty nice non-blocking pool implementation for rxjava2-jdbc so I ported it to Reactor with some modifications to make it easy to use with R2DBC.

[https://github.com/rdegnan/reactor-pool/blob/master/src/main/java/reactor/pool/NonBlockingPool.java](https://github.com/rdegnan/reactor-pool/blob/master/src/main/java/reactor/pool/NonBlockingPool.java)

I think this is a great starting point – it's got a nice builder and the pool itself is generic enough that it could go into reactor or reactor-extra. You can check out objects, then call checkin() when you’re finished and they are returned to the pool. Usage with R2DBC would look like this, for example:

![image](https://user-images.githubusercontent.com/1444984/49498802-11bcdf80-f821-11e8-8ac5-cdb8b3d91fd0.png)

**Comment by simonbasle** [comment]
We're glad to announce that the [reactor-pool](https://github.com/reactor/reactor/reactor-pool) project has now landed in our github 😄 
Please have a look and continue any discussion there.
