### ISSUE TITLE
Combine Mono.timeout makes threads hung

### ISSUE THREAD

**Issue by alset0326** [reactor/reactor#669]
Hi, I recently found a bug when I use Mono.timeout.
Let's see the code
```java
for (int i = 0; i < 100; i++) {
    Mono.just(i)
            .timeout(Duration.ofSeconds(1), Schedulers.elastic())
            .doOnNext(System.out::println)
            .block();
}
Thread.getAllStackTraces().keySet().forEach(System.out::println);
```
If you run this code, you would find out that there are so many threads with name starting with "elastic-" which is in waiting state.
It seems that on each `timeout` operation, reactor create a new thread and somehow this thread is waiting forever.
If you increase the value of the var `i` to 65535. It would throw `Exception in thread "main" java.lang.OutOfMemoryError: unable to create new native thread`.
I also tested `Mono.create` and `Mono.fromFuture`. They both behave the same.

**Comment by simonbasle** [comment]
Most operators that deal with a `Scheduler` actually pick a `Worker` of said `Scheduler` upon subscription. `Schedulers.elastic()` grows on demand, which means it creates a new `Worker` each time one is requested.

This works as intended: by using the elastic `Scheduler` you're instructing Reactor to create a new `Thread` (or `Worker`) per timeout instance.

This is the reason why the default isn't `Schedulers.elastic()` but **`Schedulers.parallel()`**, which has a bounded pool of Workers.

**Comment by alset0326** [comment]
But when my task is finished, It cannot cancel the timeout scheduler?

**Comment by simonbasle** [comment]
Not immediately, because it has a Time-To-Live. Your for loop is seen as a spike in workload from the elastic scheduler's perspective, and none of the iterations actually trigger the timeout (which is the condition for it to "release" the worker). Changing `Mono.just(i)` to `Mono.never()` will trigger the timeout and, although the test would run longer, you should see far less threads at the end.

Here is the adjusted code, with a `onErrorReturn` to avoid having block throwing a `TimeoutException`:

```java
for (int i = 0; i < 100; i++) {
    Mono.never()
            .timeout(Duration.ofSeconds(1), Schedulers.elastic())
            .onErrorReturn(i)
            .block();
}
Thread.getAllStackTraces().keySet().forEach(System.out::println);
```

**Comment by alset0326** [comment]
In my test, the elastic thread would wait forever. My test case is:
```java
for (int i = 0; i < 100; i++) {
    Mono.just(i)
            .timeout(Duration.ofMillis(2), Schedulers.elastic())
            .doOnNext(System.out::println)
            .block();
}
Thread.sleep(10000);
Thread.getAllStackTraces().keySet().forEach(System.out::println);
```

**Comment by alset0326** [comment]
It seems that task scheduler can only run on parallel or single. Nor elastic or immediate
