### ISSUE TITLE
Question about Mono's switchIfEmpty

### ISSUE THREAD

**Issue by asasas234** [reactor/reactor#671]
I want to implement

 mono.flatMap(result -> {
       If(result == xx) {
             Return monoA;
       } else {
             Return monoB;
       }
});

Optimized into

Mono.filter(result -> result == xx).flatMap(monoA).switchIfEmpty(monoB);

But the actual writing will be because monoA may be Mono.empty(); causing monoA to be executed or monoB, there is no better operator to solve this problem.

**Comment by simonbasle** [comment]
If `monoA` can be empty, then no, there isn't a better way to write this than the first `flatMap` syntax. It can be a bit abridged, like 
```java
mono.flatMap(r -> (r == xx) ? monoA : monoB)
```
but that's pretty much it.

**Comment by bsideup** [comment]
@simonbasle perhaps we should move this issue to reactor-core with GitHub's "transfer issue" feature?
