### ISSUE TITLE
rework standard set of labels across all projects

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor#673]
current state (core):
https://github.com/reactor/reactor-core/labels?page=1&sort=name-asc

we've discussed reorganizing the labels into a more codified minimum set, as well as making sure all projects use a similar approach.

 - Taking inspiration from spring-boot, the color+prefix for label categories seems like a good approach. ([spring-boot](https://github.com/spring-projects/spring-boot/labels), [spring-framework](https://github.com/spring-projects/spring-framework/labels))
 - The `/` separator should be used in favor of `:`, because the later is disruptive of github search syntax
 - core and netty at least have a very close set of labels to those of boot, but don't use a prefix and use color as a sense of "urgency" for the issue types. that information could instead be carried over with emojis
 - each project can of course have an additional subset of project-specific labels

Additional TODOs to keep in mind:
 - [x] ~reactor/reactor could only have a single `all-projects` label~ (legacy issues have legacy labels like bug/etc...)
 - [x] remove the unused / github default crust
 - [x] align on a `good-first-issue`/`help-wanted` label for 1st time contributors
 - [x] migrate `reactor-core`
 - [x] migrate `reactor-addons`
 - [x] migrate `reactor-netty`
 - [x] migrate `reactor-pool`
 - [x] migrate `reactor-kafka`
 - [x] migrate `reactor-rabbitmq`
 - [x] migrate `Blockhound`
 - [x] migrate `reactor`
 - [x] migrate `bot`
 - [x] migrate `reactor-kotlin-extensions`
 - [x] migrate `projectreactor.io`

**Comment by bsideup** [comment]
idea to consider: empty project with the labels as a template (to be used with http://www.dorukdestan.com/github-label-manager/ )

**Comment by simonbasle** [comment]
for issues marked for potential contributors, `help wanted` and `good first issue` are naturally put forward by GitHub on their own Explore interface, as well as a number of sites that allow to crawl for such issues and, last but not least, Hackathons... So we'll keep these, as the two only exceptions without a prefix.

**Comment by simonbasle** [comment]
Proposal for label "categories" (each category has a prefix with the `/` separator and a dedicated background color):

![type is #d4c5f9](https://img.shields.io/badge/type%2F-%23d4c5f9-d4c5f9)
The type of the issue. Small subset of types, one such label per issue.

The type could be later useful in producing automatic drafts of release notes.

![warn is #f49b42](https://img.shields.io/badge/warn%2F-%23f49b42-f49b42)
A qualifier of issues that require extra attention: blockers, regressions, API changes... 

Only stuff that commands attention from the users.
 - An issue _can_ have several alerts, so this was separated from `type/`
 - The `status/` color is more neutral, so having a more eye-catching color was a motivator for this category

![status is #fef2c0](https://img.shields.io/badge/status%2F-%23fef2c0-fef2c0)
Various status of an issue, including when it is closed for various reasons. 

Conceptually, an issue should only have one status at a time and move from status to status

Only exceptional resolutions that need a kind of "justification" are treated as statuses (invalid, declined, duplicate...). In other cases, the issue is simply closed with or without a commit.

![for is #c5def5](https://img.shields.io/badge/for%2F-%23c5def5-c5def5)
The issue needs a particular action.

A **common set** of action will be proposed:
  - `for/user-action` when the issue needs more feedback or the PR more work from the user
  - `for/team-attention` when the issue needs work from the team, decisions, etc...
  - `for/merge-with-rebase` when a PR contains several semantic commits that are ready to be rebased into the main branch rather than squashed
  - `for/forward-merge` when the PR has been merged into maintenance branch and needs to be forward-merged into `master`
  - etc...

In addition to that, **each project will have its own set** of `for/XXX` labels that denote "redirections" (eg. this issue is not a `reactor-netty` issue but rather a `springframework` issue: `for/springframework`).

![contributor labels are #159818](https://img.shields.io/badge/help%20wanted-%23159818-159818)
A bit of an exception: for compatibility with tools that recognize the GitHub standard `good first issue` and `help wanted` labels, we'll keep these two in the "contribution" category **without a prefix**, with green color.

![area is #d5a6bd](https://img.shields.io/badge/area%2F-%23d5a6bd-d5a6bd)
This one is always **specific to each project**. Denotes themes or functional areas of the project that issues can be split between. Eg. `java9` or `performance` or `reactor-test`.
Some project-specific categories could also be added, and it would then be recommended to choose either the `area` color (`#d5a6bd`) or a color sufficiently distinct from all the other categories.


**More design notes:**
Most existing labels should just be renamed to the new candidates. When 2+ existing labels match, rename one and move issues from the second one (preferably the one with less issues, as they will get pinged...).

Not all labels should necessarily be introduced to all projects, only the ones to be renamed. But when the need arises a project should pick one of these (or at least an existing CATEGORY)...

Some labels will be removed. Notably, the `wip` label is entirely removed and to be replaced by the use of "Draft PR" feature.

**Comment by simonbasle** [comment]
As a result of the proposal above, here is the complete set of labels identified:

label | description 
-- | --
type/bug | A general bug
type/enhancement | A general enhancement
type/doc | A documentation update
type/chore | A task not related to code (build, formatting, process, ...)
type/dependency-upgrade | A dependency upgrade
good first issue | Ideal for a new contributor, we'll help
help wanted | We need contributions on this
warn/blocker | This blocks either a release or a downstream project
warn/regression | A regression from a previous release
warn/api-change | Breaking change with compilation errors
warn/behavior-change | Breaking change of publicly advertised behavior
warn/deprecation | This issue/PR introduces deprecations
status/need-decision | This needs team attention and discussion
status/need-triage | A new issue that still need to be evaluated as a whole
status/need-investigation | This needs more in-depth investigation
status/on-hold | This was set aside or cannot be worked on yet
status/need-design | This needs more in depth design work
status/has-workaround | This has a known workaround described
status/duplicate | This is a duplicate of another issue
status/declined | We feel we shouldn't currently apply this change/suggestion
status/invalid | We don't feel this issue is valid
status/cannot-reproduce | We cannot reproduce this issue
for/fast-track | Instructs the bot to fast track
for/forward-merge | Reminder to forward merge
for/merge-with-rebase | Reminder to merge the PR in rebase mode (several semantic commits)
for/team-attention | This issue needs team attention
for/user-attention | This issue needs user attention (feedback, rework, etc...)
for/stackoverflow | Questions are best asked on SO or Gitter
for/SOME_OTHER_PROJECT | This belongs to another project...
area/SOME_THEME | This belongs to a theme or functional area of the project

**Comment by simonbasle** [comment]
This has now been done across all relevant projects 🎉 🎉

**Comment by simonbasle** [comment]
Now that GitHub supports organization-level default labels, added them to the org.
