### ISSUE TITLE
Reactor BOM has explicit scope for dependencies (should be empty)

### ISSUE THREAD

**Issue by dsyer** [reactor/reactor#677]
The problem is that any project that uses the BOM and includes reactor as a transitive dependency (in any scope) will get reactor jars in compile scope.

See https://github.com/spring-projects/spring-framework/issues/23660 for a similar problem there.

**Comment by dsyer** [comment]
Looks like it is fixed in Dysprosium. But still a problem in Californium (Spring Boot 2.1).

**Comment by wilkinsona** [comment]
This pom will reproduce the problem:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.0.BUILD-SNAPSHOT</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>dependency-scope-problem</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>dependency-scope-problem</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

`reactor-core` and `reactive-streams` end up in compile scope.

**Comment by simonbasle** [comment]
This should now be fixed in `Bismuth`, `Californium` and `Dysprosium` build snapshots. Please double check @wilkinsona or @dsyer, and thanks for all the heavy lifting @bclozel !
Note that we don't plan on releasing a Bismuth release, unless this alone is still a red flag for SPR 5.0.x / Boot 2.0.x ? Californium on the other hand is used by SPR 5.1.x/ Boot 2.1.x and is still supported.

**Comment by bclozel** [comment]
BOMs look good to me!

* https://repo.spring.io/libs-snapshot-local/io/projectreactor/reactor-bom/Dysprosium-BUILD-SNAPSHOT/reactor-bom-Dysprosium-BUILD-SNAPSHOT.pom
* https://repo.spring.io/libs-snapshot-local/io/projectreactor/reactor-bom/Californium-BUILD-SNAPSHOT/reactor-bom-Californium-BUILD-SNAPSHOT.pom
