### ISSUE TITLE
How to convert a java.util.concurrent.Future to Mono

### ISSUE THREAD

**Issue by asasas234** [reactor/reactor#685]

**Comment by ShaneLee** [comment]
Mono.fromFuture

**Comment by simonbasle** [comment]
what @ShaneLee said.
@asasas234 two things about this issue:
1. this project is hosting the BOM, so it is not the right repository
2. questions are best asked on StackOverflow or on Gitter, as mentioned in our CONTRIBUTING.md (https://github.com/reactor/.github/blob/master/CONTRIBUTING.md)

**Comment by HansOspina** [comment]
@ShaneLee but fromFuture received CompletableFuture, not Future?

**Comment by ShaneLee** [comment]
@HansOspina CompletableFuture implements Future, so Mono.fromFuture works from a CompletableFuture. Future is just an interface, so you don't get direct instantiations of Future.
