### ISSUE TITLE
Lengthen deprecation cycle

### ISSUE THREAD

**Issue by philsttr** [reactor/reactor#692]
## Motivation

I'd like project reactor to have a longer period of time between when functionality is deprecated and when it is removed.

## Desired solution

Ideally deprecated functionality would not be removed until the next _major_ release, if semantic versioning is being followed (since removal of functionality is not backwards compatible).

If waiting until the next major release is not feasible, a minimum of two point releases would be nice.

## Additional context

Project reactor is a very low level library.  By that, I mean lots of other libraries (both public, and internal) depend upon it.  When an application combines many of these libraries together that all depend on project reactor, it can be difficult to find a combination that works together well.

This is particularly painful when the deprecated functionality is heavily used (such as `.subscriberContext`, which was deprecated in 3.4, and is slated for removal in 3.5).

Lengthening the time between deprecation and removal will increase the chance of being able to find a set of libraries that work well together within a single application.

**Comment by simonbasle** [comment]
# here is the policy we're settling on:

## :recycle: Our policy on **deprecations**

When dealing with deprecations, given a version `A.B.C`, we'll ensure that:

 - deprecations introduced in version `A`.`B`.`0` will be removed **no sooner than** version `A`.**`B+1`**.`0`
 - deprecations introduced in version `A`.`B`.`1+` will be removed **no sooner than** version `A`.**`B+2`**.`0`
 - we'll strive to mention the following in the deprecation javadoc:
   - target minimum version for removal
   - pointers to replacements for the deprecated method
   - version in which method was deprecated

> This policy is officially in effect as of January 2021.

Note that deprecation removal targets are not a hard commitment, and the deprecated methods **could live on further than these minimum target GA versions** (ie. only the most problematic deprecated methods will be removed aggressively).

:warning: That said, deprecated code that has outlived its minimum removal target version may be removed in any subsequent release (including patch releases, aka service releases) without further notice. So users should still strive to update their code as early as possible.

**Comment by simonbasle** [comment]
- [x] Add the policy to common `SUPPORT.md` and common `CONTRIBUTING.md` (reactor/.github#12)
- [ ] Add the policy to reactor-netty's own repo-specific `CONTRIBUTING.md`
- [ ] Add pointers to the policy in reactor-core's reference documentation and/or README
- [ ]

**Comment by simonbasle** [comment]
This can now be closed as the policy is made visible in 3.3.13.RELEASE+ reference guide (and 3.4.2+)
