### ISSUE TITLE
TIMED_WAITING

### ISSUE THREAD

**Issue by adrklang** [reactor/reactor#693]
I use the swagger accessed by the Google browser to request the project created by WebFlux,I use JConsole to monitor the number of threads running in the project, and it will be found that each request is removed and a thread will be created. When the request is finished, the thread will be in the state of TIMED_WAITING and will not be closed, which will cause more and more threads to be created. I don't know what is the problem, can you help me to answer it

This is the thread part I looked at using the JConsole tool

Name: `boundedElastic - evictor - 811`

Status: Java. Util. Concurrent. The locks. AbstractQueuedSynchronizer $ConditionObject @ 741026 TIMED_WAITING b5

Total stop number: 0, total wait number: 25

Stack trace:

java.base@11.0.1 / JDK. Internal. Misc. Unsafe. Park (Native Method)

java.base@11.0.1 / Java. Util. Concurrent. The locks. LockSupport. ParkNanos (LockSupport. Java: 234)

java.base@11.0.1 / Java. Util. Concurrent. The locks. AbstractQueuedSynchronizer $ConditionObject. AwaitNanos (AbstractQueuedSynchronizer. Java: 2123)

java.base@11.0.1 / Java. Util. Concurrent. ScheduledThreadPoolExecutor $DelayedWorkQueue. Take (ScheduledThreadPoolExecutor. Java: 1182)

java.base@11.0.1 / Java. Util. Concurrent. ScheduledThreadPoolExecutor $DelayedWorkQueue. Take (ScheduledThreadPoolExecutor. Java: 899)

java.base@11.0.1 / Java. Util. Concurrent. ThreadPoolExecutor. GetTask (ThreadPoolExecutor. Java: 1054)

java.base@11.0.1 / Java. Util. Concurrent. ThreadPoolExecutor. RunWorker (ThreadPoolExecutor. Java: 1114)

java.base@11.0.1 / Java. Util. Concurrent. ThreadPoolExecutor $Worker. The run (ThreadPoolExecutor. Java: 628)

java.base@11.0.1 / Java. Lang. Thread. The run (Thread. Java: 834)

**Comment by violetagg** [comment]
@adrklang You didn't specify the Spring Framework version, so is it possible that you are facing this issue in Spring Framework? -> https://github.com/spring-projects/spring-framework/issues/26263

**Comment by adrklang** [comment]
@violetagg The spring-boot version I use is 2.4.1. If I use the browser request, it will increase the thread continuously, but I use JMeter test does not increase the thread

**Comment by violetagg** [comment]
@adrklang Please update your Spring Boot version so that we are sure that it is not related to that issue.

**Comment by adrklang** [comment]
This issue has been fixed since I updated to version 2.4.2

**Comment by adrklang** [comment]
@violetagg Thanks to answer
