### ISSUE TITLE
[Reactor Gen4] The Rationale for a Generation 4 of Reactor

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor#705]
This issue exposes the general rationale for a Generation 4 of Reactor.

Below are other issues around that topic, which focus on more specific aspects:
 - [#704] Reactor 3 must be able to run alongside Reactor 4
 - [#703] JDK 17 baseline
 - ...

## Preamble: What of Reactor 3

We want to start by making one thing clear: Reactor 3 isn't going away.

The current plan is that the `Europium` line (aka BOM `2020.0.x`, aka reactor-core `3.4.x`) is going to be turned into an LTS,
with support extended for at least a couple of years past the GA release of Reactor 4.

We thought about a 3.5.x LTS, but compared to turning Europium into LTS it doesn't bring much to the table.

Actually, since there would be no Spring release to consume it, it would be invisible to a majority of our user base.
(yes, we have users that directly depend on Reactor rather than through Spring, but given the pervasiveness of the framework,
we can expect that in the end not a lot of applications using Reactor are completely Spring-free...

With an LTS, we give users that cannot upgrade to the next generation a way out.

But it becomes important that Reactor 3 can run alongside Reactor 4 for that to be a practical option.

Issue https://github.com/reactor/reactor/issues/704 is focusing on that aspect.

## Internal "protocol" rework

When a `Reactor` `Subscriber` connects with a `Reactor` `Publisher`, they recognize that they are part of the same library
and as such can relax a bit wrt Reactive Streams protocol, by making some assumptions about how the other party is implemented.

It also enables some sort of Reactor-specific RS protocol.
For instance, operator fusion becomes possible (which improves performance), `Context` is made accessible to the `Subscription`s,
etc...

With some R&D, these internal protocols could be improved in order to better integrate modern concerns like:
 - `Context` propagation
 - observability (tracing, logging, metrics)
 - lifecycle management and avoiding leaks (`doOnDiscard`)
 - ...

In the current state, we feel we've come to the limit of what can be done in Reactor 3.
By giving ourselves the opportunity to break the current internals, there's more room for innovative solutions to these problems.

## Changes to the original tradeoffs

When Reactor 3 was designed, a number of trade offs were made.
Notably, one around balancing performance vs user-driven backpressure.

After 5 years, we now think different tradeoffs now make more sense.

Since these can lead to subverted expectations around "the default behavior"
of a `Flux` or `Mono`, there is absolutely no way they can be introduced in
a Reactor 3 release.

Ideas include:

 - reduce the amount of implicit backpressure (aka prefetch)
 - make `Mono` even lazier (by triggering behavior on first request rather than subscription)

## Netty 5

Reactor is applicable to many domains, but network I/O is a huge one among these.
No wonder `Reactor-Netty` is only second to `Reactor-Core` in the portfolio of projects.

`Netty 5` is the next generation of non-blocking network I/O libraries.
But `Reactor-Netty` exposes a lot of `Netty` concepts and classes, translating the rest into reactive APIs.
As such, `Reactor-Netty` `1.x` cannot really switch to Netty 5 without breakage.

This implies a `Reactor-Netty` 2.x generation.

Since Netty 5 will be baselined on **Java 11**, this also implies a similar baseline change in `Reactor-Netty`
(which could only happen in a new generation anyway).

## Spring 6

Last but not least, a majority of our user base either directly comes from Spring or uses Reactor in the context of a Spring-based application.

Even though Reactor doesn't depend on the Spring ecosystem, Spring Framework/Boot/Data/Gateway/... have all immensely contributed to the success of the library.
They are important stakeholders, and if there isn't a Spring release that is going to use our stuff, then it begs some questioning on our part as to whether that stuff is needed...

Spring 6 is currently being developed, and this provides us with a unique window of opportunity to make these large changes in a way they will get to an benefit a large number of people.

For this version, Spring is establishing a Java 17 baseline.

Since we'll need to change the Java baseline to 11 to support Netty 5, we might as well go the extra mile and choose **Java 17** instead.

By the time Reactor 4 is finally out next year, Java 11 will already be (close to) end of support.

We believe this is a bold move, but that it is the right move.

See the discussion in https://github.com/reactor/reactor/issues/703 around Java 17 specifically.

## Opportunity for other (smaller-scale) changes

There are other changes that could probably be done in Reactor 3, but would actually make better sense in a Gen4:
 - entirely new APIs / operators
 - grouping some operators under API groups
 - using more builder / spec patterns
 - `Message`-like API to pass data and metadata (from the `Context`)
 - new types of macro-fusion across different operators
 - graph materialization and introspection

Gen4 would also be a good opportunity to prune the codebase of all current deprecations.

**Comment by bric3** [comment]
In terms of smaller scale change. I always thought that RxJava observable types described better the semantics of the stream.

* A `Completable` will either complete or error.
* A `Maybe` will either return something or not then complete, or error.
* A `Single` will either return something then complete, or error.

These types immediately describe the method, valid operations are limited by the time type system. While a `Mono` always requires some inspection to get the stream semantics, and eventually requires to apply defensive technics.

I understand this significantly expand the API surface, for integrators as well, yet I'd like to believe the safety of these types outweigh this cost.

**Comment by simonbasle** [comment]
## :loudspeaker: Reactor 2022.0 to stay at Reactor 3 generation level

After much debate, prioritizing the topics we most want to see for the next 2022.0 train,
taking into account the feedback from our community and evaluating the risk/benefits of a new architecture / a new Java baseline,
we've finally reached a decision for the next version of Reactor.

**The `2022.0` release train line will continue with the same Reactor 3 architecture and Java baseline.**

### What it means for Reactor-Core and Reactor-Netty

As such, Reactor-Core will continue the 3.x line with a 3.5.0.
Reactor-Netty will however split into two stacks: one for Netty 4, continuing the 1.x line with a 1.1.0, and one for Netty 5.
The later stack will likely be separate modules, with their own versioning.

To be perfectly clear: the Java baseline for the 2022.0 train will still be Java 8.
The only exception is Reactor-Netty for Netty5, which will require Java 17.

This release train line will focus on:
* offering a Netty 5 stack
* improving performance and internal RS optimizations
* integrating efforts around observability
* improving the user experience when mixing imperative and reactive code (particularly with thread locals)

### Looking ahead, past Java 8

As we cannot stay on Java 8 forever, the team thinks there should be at least a tentative plan for upgrading.
We expect a discussion around Java baseline upgrade should occur again as we get closer to the next LTS, Java 21, *in parallel to the present continuation of Reactor 3 generation*.
This might be pushed a little if we foresee a subsequent Java version is likely to drive much more adoption than Java 21.

This gives our users and ecosystem outside of Spring an additional 2 years to plan around this Java upgrade.

For core, it would represent a 4.0.0.
Note that it might also be an opportunity for much deeper API and architectural changes, representing a new generation of Reactor, but that decision will come much later.

**Comment by JonathanGiles** [comment]
Thank you for taking community feedback and making this choice. I know it would not have been an easy decision, or the 'fun' decision, but from a community support standpoint I believe you've absolutely made the best call. Thank you.
