### ISSUE TITLE
Is there any connection between   org.projectreactor:reactor-core and io.projectreactor:reactor-core ?

### ISSUE THREAD

**Issue by huanglongyue** [reactor/reactor#711]
Is there any connection between   org.projectreactor:reactor-core and io.projectreactor:reactor-core ？？？

**Comment by OlegDokuka** [comment]
Hey!

As far as I know we do not publish anything under `org.` package

**Comment by simonbasle** [comment]
@huanglongyue there is a connection, but distant: these are the coordinates for the first generation of the reactor project (between 2013 and 2015). This was nothing like what reactor-core is today, and this was before reactive programming / reactive streams.
