### ISSUE TITLE
support logback Groovy DSL in reactor-logback

### ISSUE THREAD

**Issue by raysuliteanu** [reactor/reactor#81]
as is your XML-based logback configuration doesn't work when translated to logback's Groovy DSL. I tried this after converting the example XML config using logback's utility http://logback.qos.ch/translator/asGroovy.html

**Comment by AlexCzar** [comment]
Why is this issue closed? It is still not possible to configure `appenderRef` with `reactor.logback.AsyncAppender`.

**Comment by smaldini** [comment]
My bad

**Comment by AlexCzar** [comment]
After some research and source digging I've uncovered that logback guys fixed it themselves in 1.1.3. The fix is already in their master branch. Sorry for 'issue necromancy' :)

**Comment by ifesdjeen** [comment]
:+1:
